SET DEFINE OFF;
INSERT INTO company_table values( 1, 'Valve');
INSERT INTO company_table values( 2, 'Facepunch Studios');
INSERT INTO company_table values( 3, 'Firaxis Games');
INSERT INTO company_table values( 4, 'Aspyr (Mac, Linux)');
INSERT INTO company_table values( 5, 'Relic Entertainment');
INSERT INTO company_table values( 6, 'Re-Logic');
INSERT INTO company_table values( 7, 'Bohemia Interactive');
INSERT INTO company_table values( 8, 'Paradox Development Studio');
INSERT INTO company_table values( 9, 'Daybreak Game Company');
INSERT INTO company_table values( 10, 'Torn Banner Studios');
INSERT INTO company_table values( 11, 'SCS Software');
INSERT INTO company_table values( 12, 'Gaijin Entertainment');
INSERT INTO company_table values( 13, 'The Behemoth');
INSERT INTO company_table values( 14, 'Nicalis, Inc.');
INSERT INTO company_table values( 15, 'Hanako Games');
INSERT INTO company_table values( 16, 'Unknown Worlds Entertainment');
INSERT INTO company_table values( 17, 'Firaxis');
INSERT INTO company_table values( 18, 'Feral Interactive (Mac)');
INSERT INTO company_table values( 19, 'Feral Interactive (Linux)');
INSERT INTO company_table values( 20, 'StudioMDHR Entertainment Inc.');
INSERT INTO company_table values( 21, '11 bit studios');
INSERT INTO company_table values( 22, 'Pocketwatch Games');
INSERT INTO company_table values( 23, 'Powerhoof');
INSERT INTO company_table values( 24, 'Ludeon Studios');
INSERT INTO company_table values( 25, 'RobTop Games');
INSERT INTO company_table values( 26, 'Image & Form');
INSERT INTO company_table values( 27, 'Klei Entertainment');
INSERT INTO company_table values( 28, 'Studio Wildcard');
INSERT INTO company_table values( 29, 'Instinct Games');
INSERT INTO company_table values( 30, 'Efecto Studios');
INSERT INTO company_table values( 31, 'Virtual Basement LLC');
INSERT INTO company_table values( 32, 'CyberConnect2 Co. Ltd.');
INSERT INTO company_table values( 33, 'Ubisoft Montreal');
INSERT INTO company_table values( 34, 'System Era Softworks');
INSERT INTO company_table values( 35, 'Dry Cactus');
INSERT INTO company_table values( 36, 'Team Cherry');
INSERT INTO company_table values( 37, 'FromSoftware, Inc.');
INSERT INTO company_table values( 38, 'Slightly Mad Studios');
INSERT INTO company_table values( 39, 'Moon Studios GmbH');
INSERT INTO company_table values( 40, 'BANDAI NAMCO Studios Inc.');
INSERT INTO company_table values( 41, 'tobyfox');
INSERT INTO company_table values( 42, 'AMPLITUDE Studios');
INSERT INTO company_table values( 43, 'CreSpirit');
INSERT INTO company_table values( 44, 'GemaYue');
INSERT INTO company_table values( 45, 'Dylan Fitterer');
INSERT INTO company_table values( 46, 'ConcernedApe');
INSERT INTO company_table values( 47, 'Wube Software LTD.');
INSERT INTO company_table values( 48, 'Larian Studios');
INSERT INTO company_table values( 49, 'Survios');
INSERT INTO company_table values( 50, 'Sukeban Games');
INSERT INTO company_table values( 51, 'Code Horizon');
INSERT INTO company_table values( 52, 'Trinket Studios');
INSERT INTO company_table values( 53, 'QLOC');
INSERT INTO company_table values( 54, 'DIMPS');
INSERT INTO company_table values( 55, 'Defiant Development');
INSERT INTO company_table values( 56, 'Halfbrick Studios Pty Ltd');
INSERT INTO company_table values( 57, 'Frontier Developments');
INSERT INTO company_table values( 58, 'Noio');
INSERT INTO company_table values( 59, 'Toast');
INSERT INTO company_table values( 60, 'ProGames Studio');
INSERT INTO company_table values( 61, 'COLOPL, Inc.');
INSERT INTO company_table values( 62, 'Wargaming Group Limited');
INSERT INTO company_table values( 63, 'Project Moon');
INSERT INTO company_table values( 64, 'SNK CORPORATION');
INSERT INTO company_table values( 65, 'Abstraction Games');
INSERT INTO company_table values( 66, 'Visual Concepts');
INSERT INTO company_table values( 67, 'Christian Whitehead');
INSERT INTO company_table values( 68, 'Headcannon');
INSERT INTO company_table values( 69, 'PagodaWest Games');
INSERT INTO company_table values( 70, 'Anvil Game Studios');
INSERT INTO company_table values( 71, 'Konami Digital Entertainment Co., Ltd.');
INSERT INTO company_table values( 72, 'Creative Assembly');
INSERT INTO company_table values( 73, 'Konami Digital Entertainment');
INSERT INTO company_table values( 74, 'Sports Interactive');
INSERT INTO company_table values( 75, 'TT Games');
INSERT INTO company_table values( 76, 'Lighthouse Games Studio');
INSERT INTO company_table values( 77, 'Landfall West');
INSERT INTO company_table values( 78, 'ß¾ú­«¢«ê«¹ü³äÅ?');
SET DEFINE ON;
