SET DEFINE OFF;
INSERT INTO company_table values( 1, 'Valve');
INSERT INTO company_table values( 2, 'Gearbox Software');
INSERT INTO company_table values( 3, 'Tripwire Interactive');
INSERT INTO company_table values( 4, 'id Software');
INSERT INTO company_table values( 5, 'Infinity Ward');
INSERT INTO company_table values( 6, 'Aspyr (Mac)');
INSERT INTO company_table values( 7, 'Frontier');
INSERT INTO company_table values( 8, 'PopCap Games, Inc.');
INSERT INTO company_table values( 9, 'Elixir Studios');
INSERT INTO company_table values( 10, 'Double Fine Productions');
INSERT INTO company_table values( 11, 'Facepunch Studios');
INSERT INTO company_table values( 12, 'Relic Entertainment');
INSERT INTO company_table values( 13, 'The Creative Assembly');
INSERT INTO company_table values( 14, 'Feral Interactive (Mac)');
INSERT INTO company_table values( 15, 'Feral Interactive (Linux)');
INSERT INTO company_table values( 16, 'GSC Game World');
INSERT INTO company_table values( 17, 'Pandemic Studios');
INSERT INTO company_table values( 18, 'Pyro Studios');
INSERT INTO company_table values( 19, 'Io-Interactive A/S');
INSERT INTO company_table values( 20, 'Ion Storm');
INSERT INTO company_table values( 21, 'Nadeo');
INSERT INTO company_table values( 22, 'CCP');
INSERT INTO company_table values( 23, 'Firaxis Games');
INSERT INTO company_table values( 24, 'Irrational Games');
INSERT INTO company_table values( 25, 'Virtual Programming (Linux)');
INSERT INTO company_table values( 26, 'Aspyr (Mac, Linux)');
INSERT INTO company_table values( 27, 'Gray Matter Studios');
INSERT INTO company_table values( 28, 'Gas Powered Games');
INSERT INTO company_table values( 29, 'Treyarch');
INSERT INTO company_table values( 30, 'Dylan Fitterer');
INSERT INTO company_table values( 31, 'Epic Games, Inc.');
INSERT INTO company_table values( 32, 'Feral Interactive (Mac/Linux)');
INSERT INTO company_table values( 33, 'Maxis¢â');
INSERT INTO company_table values( 34, 'EA Redwood Shores');
INSERT INTO company_table values( 35, 'Hidden Path Entertainment');
INSERT INTO company_table values( 36, 'TaleWorlds Entertainment');
INSERT INTO company_table values( 37, 'Frictional Games');
INSERT INTO company_table values( 38, 'ACE Team');
INSERT INTO company_table values( 39, 'Bethesda Game Studios¢ç');
INSERT INTO company_table values( 40, 'Bethesda Game Studios');
INSERT INTO company_table values( 41, 'Obsidian Entertainment');
INSERT INTO company_table values( 42, 'Haemimont Games');
INSERT INTO company_table values( 43, 'EA - Maxis');
INSERT INTO company_table values( 44, 'EA Los Angeles');
INSERT INTO company_table values( 45, 'DICE');
INSERT INTO company_table values( 46, 'BioWare');
INSERT INTO company_table values( 47, 'LucasArts');
INSERT INTO company_table values( 48, 'Ubisoft Montreal');
INSERT INTO company_table values( 49, 'Rocksteady Studios');
INSERT INTO company_table values( 50, 'Frozenbyte');
INSERT INTO company_table values( 51, 'Amanita Design');
INSERT INTO company_table values( 52, 'Team Meat');
INSERT INTO company_table values( 53, 'Croteam');
INSERT INTO company_table values( 54, 'Sledgehammer Games');
INSERT INTO company_table values( 55, 'Arrowhead Game Studios');
INSERT INTO company_table values( 56, 'Paradox Development Studio');
INSERT INTO company_table values( 57, 'Codemasters Racing');
INSERT INTO company_table values( 58, 'Visceral Games');
INSERT INTO company_table values( 59, 'Criterion Games');
INSERT INTO company_table values( 60, 'The Sims Studio');
INSERT INTO company_table values( 61, 'Cold Beam Games');
INSERT INTO company_table values( 62, 'Volition');
INSERT INTO company_table values( 63, 'Terry Cavanagh');
INSERT INTO company_table values( 64, 'EasyGameStation');
INSERT INTO company_table values( 65, 'SEGA');
INSERT INTO company_table values( 66, 'Devil''s Details');
INSERT INTO company_table values( 67, 'Coffee Stain Studios');
INSERT INTO company_table values( 68, 'Zachtronics');
INSERT INTO company_table values( 69, 'Final Form Games');
INSERT INTO company_table values( 70, 'Messhof');
INSERT INTO company_table values( 71, 'Stainless Games');
INSERT INTO company_table values( 72, 'Gaslamp Games, Inc.');
INSERT INTO company_table values( 73, 'Ensemble Studios');
INSERT INTO company_table values( 74, 'Re-Logic');
INSERT INTO company_table values( 75, 'Supergiant Games');
INSERT INTO company_table values( 76, 'Zeboyd Games');
INSERT INTO company_table values( 77, 'The Indie Stone');
INSERT INTO company_table values( 78, 'Pocketwatch Games');
INSERT INTO company_table values( 79, 'Edmund McMillen and Florian Himsl');
INSERT INTO company_table values( 80, 'Runic Games');
INSERT INTO company_table values( 81, 'Robot Entertainment');
INSERT INTO company_table values( 82, 'Machine Games');
INSERT INTO company_table values( 83, 'Arkane Studios');
INSERT INTO company_table values( 84, 'Suspicious Developments');
INSERT INTO company_table values( 85, 'Freebird Games');
INSERT INTO company_table values( 86, 'BlinkWorks Media');
INSERT INTO company_table values( 87, 'Nihon Falcom');
INSERT INTO company_table values( 88, 'Telltale Games');
INSERT INTO company_table values( 89, 'Muse Games');
INSERT INTO company_table values( 90, 'Love Conquers All Games');
INSERT INTO company_table values( 91, 'Chucklefish');
INSERT INTO company_table values( 92, 'Sumo Digital');
INSERT INTO company_table values( 93, 'Subset Games');
INSERT INTO company_table values( 94, 'Daybreak Game Company');
INSERT INTO company_table values( 95, 'Level Up Labs, LLC');
INSERT INTO company_table values( 96, 'Torn Banner Studios');
INSERT INTO company_table values( 97, 'Crate Entertainment');
INSERT INTO company_table values( 98, 'Squad');
INSERT INTO company_table values( 99, 'Ubisoft Montreal, Massive Entertainment, and Ubisoft Shanghai');
INSERT INTO company_table values( 100, 'Ninja Theory');
INSERT INTO company_table values( 101, 'Galactic Cafe');
INSERT INTO company_table values( 102, 'Code Mystics');
INSERT INTO company_table values( 103, 'Eugen Systems');
INSERT INTO company_table values( 104, 'New World Interactive');
INSERT INTO company_table values( 105, 'SNK Playmore');
INSERT INTO company_table values( 106, 'Polytron Corporation');
INSERT INTO company_table values( 107, 'Rebellion');
INSERT INTO company_table values( 108, 'SCS Software');
INSERT INTO company_table values( 109, 'Reto-Moto');
INSERT INTO company_table values( 110, 'Iron Galaxy Studios');
INSERT INTO company_table values( 111, 'Giant Army');
INSERT INTO company_table values( 112, 'Wolfire Games');
INSERT INTO company_table values( 113, 'CyberConnect2 Co. Ltd.');
INSERT INTO company_table values( 114, 'Ubisoft Toronto');
INSERT INTO company_table values( 115, 'Humble Hearts LLC');
INSERT INTO company_table values( 116, 'Gaijin Entertainment');
INSERT INTO company_table values( 117, 'Mine Loader Software Co., Ltd.');
INSERT INTO company_table values( 118, 'Red Barrels');
INSERT INTO company_table values( 119, 'The Behemoth');
INSERT INTO company_table values( 120, '3909');
INSERT INTO company_table values( 121, 'Vlambeer');
INSERT INTO company_table values( 122, 'Carlsen Games');
INSERT INTO company_table values( 123, 'Shining Rock Software LLC');
INSERT INTO company_table values( 124, 'Kunos Simulazioni');
INSERT INTO company_table values( 125, 'Lab Zero Games');
INSERT INTO company_table values( 126, 'Ironhide Game Studio');
INSERT INTO company_table values( 127, 'Ndemic Creations');
INSERT INTO company_table values( 128, 'Studio Bean');
INSERT INTO company_table values( 129, 'Deep Silver Volition');
INSERT INTO company_table values( 130, 'Hopoo Games, LLC');
INSERT INTO company_table values( 131, 'Priority Interrupt');
INSERT INTO company_table values( 132, 'DotEmu');
INSERT INTO company_table values( 133, 'Nicalis, Inc.');
INSERT INTO company_table values( 134, 'Hanako Games');
INSERT INTO company_table values( 135, 'Image & Form');
INSERT INTO company_table values( 136, 'Psyonix, Inc.');
INSERT INTO company_table values( 137, 'Colossal Order Ltd.');
INSERT INTO company_table values( 138, 'Ubisoft Montr?al');
INSERT INTO company_table values( 139, 'JoWooD Vienna');
INSERT INTO company_table values( 140, 'Xtal Sword');
INSERT INTO company_table values( 141, 'Red Hook Studios');
INSERT INTO company_table values( 142, 'Oovee¢ç Game Studios');
INSERT INTO company_table values( 143, 'Arc System Works');
INSERT INTO company_table values( 144, 'Unknown Worlds Entertainment');
INSERT INTO company_table values( 145, 'Matt Roszak');
INSERT INTO company_table values( 146, 'Thomas Bowker');
INSERT INTO company_table values( 147, 'Defiant Development');
INSERT INTO company_table values( 148, 'StudioMDHR Entertainment Inc.');
INSERT INTO company_table values( 149, 'Elias Viglione');
INSERT INTO company_table values( 150, 'Jussi Kukkonen');
INSERT INTO company_table values( 151, 'Pixel Ferrets');
INSERT INTO company_table values( 152, 'Laminar Research');
INSERT INTO company_table values( 153, 'SFB Games');
INSERT INTO company_table values( 154, 'Free Lives');
INSERT INTO company_table values( 155, 'Vanguard Games');
INSERT INTO company_table values( 156, '343 Industries');
INSERT INTO company_table values( 157, 'KOEI TECMO GAMES CO., LTD.');
INSERT INTO company_table values( 158, 'Alastair John Jack');
INSERT INTO company_table values( 159, 'Dreamworlds');
INSERT INTO company_table values( 160, '11 bit studios');
INSERT INTO company_table values( 161, 'Chris Sawyer Productions');
INSERT INTO company_table values( 162, 'Berserk Games');
INSERT INTO company_table values( 163, '4A Games');
INSERT INTO company_table values( 164, 'DigiFX Interactive');
INSERT INTO company_table values( 165, 'Konami Digital Entertainment');
INSERT INTO company_table values( 166, 'Dinosaur Polo Club');
INSERT INTO company_table values( 167, 'Fireproof Games');
INSERT INTO company_table values( 168, 'Lionhead Studios');
INSERT INTO company_table values( 169, 'Firaxis');
INSERT INTO company_table values( 170, 'League of Geeks');
INSERT INTO company_table values( 171, 'Counterplay Games Inc.');
INSERT INTO company_table values( 172, 'Powerhoof');
INSERT INTO company_table values( 173, 'Ludeon Studios');
INSERT INTO company_table values( 174, 'Andy Wallace');
INSERT INTO company_table values( 175, 'Team Junkfish');
INSERT INTO company_table values( 176, 'Cavedog Entertainment');
INSERT INTO company_table values( 177, 'Ubisoft Montreal, Red Storm, Shanghai, Toronto, Kiev');
INSERT INTO company_table values( 178, 'Ole Lange');
INSERT INTO company_table values( 179, 'Crytek');
INSERT INTO company_table values( 180, 'Fabio Ferrara');
INSERT INTO company_table values( 181, 'Trion Worlds');
INSERT INTO company_table values( 182, 'Ubisoft Quebec');
INSERT INTO company_table values( 183, 'Blue Byte');
INSERT INTO company_table values( 184, 'Failbetter Games');
INSERT INTO company_table values( 185, 'Smartly Dressed Games');
INSERT INTO company_table values( 186, 'Hinterland Studio Inc.');
INSERT INTO company_table values( 187, 'Deli Interactive LLC');
INSERT INTO company_table values( 188, 'CreativeForge Games');
INSERT INTO company_table values( 189, 'Mediatonic');
INSERT INTO company_table values( 190, 'Hato Moa');
INSERT INTO company_table values( 191, 'The Irregular Corporation');
INSERT INTO company_table values( 192, '07th Expansion');
INSERT INTO company_table values( 193, 'Codemasters Racing Studio');
INSERT INTO company_table values( 194, 'Capcom');
INSERT INTO company_table values( 195, 'Ubisoft Sofia');
INSERT INTO company_table values( 196, 'Ubisoft Kiev');
INSERT INTO company_table values( 197, 'Dodge Roll');
INSERT INTO company_table values( 198, 'Beam Team Games');
INSERT INTO company_table values( 199, 'Microsoft Game Studios');
INSERT INTO company_table values( 200, 'Sharpened Edge Studios');
INSERT INTO company_table values( 201, 'minori');
INSERT INTO company_table values( 202, 'VisualArts/Key');
INSERT INTO company_table values( 203, 'Cross-Product');
INSERT INTO company_table values( 204, 'Heartbit Interactive');
INSERT INTO company_table values( 205, 'Scott Cawthon');
INSERT INTO company_table values( 206, 'DONTNOD Entertainment');
INSERT INTO company_table values( 207, 'Batterystaple Games');
INSERT INTO company_table values( 208, 'Fire Hose Games');
INSERT INTO company_table values( 209, 'RobTop Games');
INSERT INTO company_table values( 210, 'Klei Entertainment');
INSERT INTO company_table values( 211, 'Indimo Labs LLC');
INSERT INTO company_table values( 212, 'THQ Nordic');
INSERT INTO company_table values( 213, 'Slick Entertainment Inc.');
INSERT INTO company_table values( 214, 'CAPCOM Co., Ltd.');
INSERT INTO company_table values( 215, 'Infinity Plus 2');
INSERT INTO company_table values( 216, 'Anisoptera Games');
INSERT INTO company_table values( 217, 'HandMade Game');
INSERT INTO company_table values( 218, 'Soviet Games');
INSERT INTO company_table values( 219, 'Forgotten Key');
INSERT INTO company_table values( 220, 'Thomas Happ Games LLC');
INSERT INTO company_table values( 221, 'Freehold Games');
INSERT INTO company_table values( 222, 'Splash Damage');
INSERT INTO company_table values( 223, 'BlankMediaGames');
INSERT INTO company_table values( 224, 'Trese Brothers');
INSERT INTO company_table values( 225, 'Dingaling');
INSERT INTO company_table values( 226, 'Sujin Ri');
INSERT INTO company_table values( 227, 'Yunjeong Yun');
INSERT INTO company_table values( 228, 'Hyein Go');
INSERT INTO company_table values( 229, 'Minsu Ock');
INSERT INTO company_table values( 230, 'Marcos Arroyo');
INSERT INTO company_table values( 231, 'Seona Lee');
INSERT INTO company_table values( 232, 'Sohyeon Jeon');
INSERT INTO company_table values( 233, 'Choice of Games');
INSERT INTO company_table values( 234, 'KIXEYE');
INSERT INTO company_table values( 235, 'Pixellore');
INSERT INTO company_table values( 236, 'Sun-Studios');
INSERT INTO company_table values( 237, 'Eggcode');
INSERT INTO company_table values( 238, 'Leslaw Sliwko');
INSERT INTO company_table values( 239, 'Steel Crate Games');
INSERT INTO company_table values( 240, 'David Stark');
INSERT INTO company_table values( 241, 'Shorebound Studios');
INSERT INTO company_table values( 242, 'Cat5Games');
INSERT INTO company_table values( 243, 'ALICE IN DISSONANCE');
INSERT INTO company_table values( 244, 'Frontwing');
INSERT INTO company_table values( 245, 'WayForward');
INSERT INTO company_table values( 246, 'Spiderling Studios');
INSERT INTO company_table values( 247, 'Studio Wildcard');
INSERT INTO company_table values( 248, 'Instinct Games');
INSERT INTO company_table values( 249, 'Efecto Studios');
INSERT INTO company_table values( 250, 'Virtual Basement LLC');
INSERT INTO company_table values( 251, 'ÍÔÍÅ??êÍ??');
INSERT INTO company_table values( 252, 'Ð¹í­Úì');
INSERT INTO company_table values( 253, 'Niffler Ltd.');
INSERT INTO company_table values( 254, 'Zeiva Inc');
INSERT INTO company_table values( 255, 'Littlewitch');
INSERT INTO company_table values( 256, 'MachineGames');
INSERT INTO company_table values( 257, 'Grey Alien Games');
INSERT INTO company_table values( 258, 'Ellada Games');
INSERT INTO company_table values( 259, 'Abnormal Software');
INSERT INTO company_table values( 260, 'Holy Priest');
INSERT INTO company_table values( 261, 'Funatics Software');
INSERT INTO company_table values( 262, 'Four Quarters');
INSERT INTO company_table values( 263, 'Zandel Media');
INSERT INTO company_table values( 264, 'Rumpus');
INSERT INTO company_table values( 265, 'Dancing Dragon Games');
INSERT INTO company_table values( 266, 'Totally Games');
INSERT INTO company_table values( 267, 'Lukas Jaeckel');
INSERT INTO company_table values( 268, 'Twelve Tiles');
INSERT INTO company_table values( 269, 'Valsar');
INSERT INTO company_table values( 270, 'Brainchild');
INSERT INTO company_table values( 271, 'Chris Sawyer');
INSERT INTO company_table values( 272, 'Walter Machado');
INSERT INTO company_table values( 273, 'Eric Hornby');
INSERT INTO company_table values( 274, 'David Szymanski');
INSERT INTO company_table values( 275, 'Interplay Entertainment Corp.');
INSERT INTO company_table values( 276, 'InvertMouse');
INSERT INTO company_table values( 277, 'Frogsong Studios AB');
INSERT INTO company_table values( 278, 'Moppin');
INSERT INTO company_table values( 279, 'System Era Softworks');
INSERT INTO company_table values( 280, 'oddonegames');
INSERT INTO company_table values( 281, 'Bare Mettle Entertainment');
INSERT INTO company_table values( 282, 'Coredumping');
INSERT INTO company_table values( 283, 'Killmonday Games AB');
INSERT INTO company_table values( 284, 'Crowbar Collective');
INSERT INTO company_table values( 285, 'NeoNight');
INSERT INTO company_table values( 286, 'Clever-Plays');
INSERT INTO company_table values( 287, 'Playsaurus');
INSERT INTO company_table values( 288, 'Shiver Games');
INSERT INTO company_table values( 289, 'John Wizard');
INSERT INTO company_table values( 290, 'Creative Assembly');
INSERT INTO company_table values( 291, 'Legend Studio');
INSERT INTO company_table values( 292, 'Zoo Corporation');
INSERT INTO company_table values( 293, 'Panic Ensues Software');
INSERT INTO company_table values( 294, 'Chu-3');
INSERT INTO company_table values( 295, 'Bakufu Narayama');
INSERT INTO company_table values( 296, 'Team Fractal Alligator');
INSERT INTO company_table values( 297, 'Massive Entertainment');
INSERT INTO company_table values( 298, 'Vasily Voronkov');
INSERT INTO company_table values( 299, 'Ryan Joseph');
INSERT INTO company_table values( 300, 'Peter Kosyh');
INSERT INTO company_table values( 301, 'Pixel Prophecy');
INSERT INTO company_table values( 302, 'Dry Cactus');
INSERT INTO company_table values( 303, 'Team Cherry');
INSERT INTO company_table values( 304, 'Maciej Targoni');
INSERT INTO company_table values( 305, 'Wojciech Wasiak');
INSERT INTO company_table values( 306, 'Radical Fish Games');
INSERT INTO company_table values( 307, 'Robot Gentleman');
INSERT INTO company_table values( 308, 'Sam Barlow');
INSERT INTO company_table values( 309, 'Andrettin');
INSERT INTO company_table values( 310, 'John Cullen');
INSERT INTO company_table values( 311, 'Visual Concepts');
INSERT INTO company_table values( 312, 'Clifftop Games');
INSERT INTO company_table values( 313, 'Deion Mobile');
INSERT INTO company_table values( 314, 'Blake Garner');
INSERT INTO company_table values( 315, 'FIVE-BN GAMES');
INSERT INTO company_table values( 316, 'Larian Studios');
INSERT INTO company_table values( 317, 'Capribyte Studios');
INSERT INTO company_table values( 318, '¡â¡Û¡à¡¿ (Miwashiba)');
INSERT INTO company_table values( 319, 'Keen Games');
INSERT INTO company_table values( 320, 'FromSoftware, Inc.');
INSERT INTO company_table values( 321, 'Subworld');
INSERT INTO company_table values( 322, 'Creoteam');
INSERT INTO company_table values( 323, 'Anarchy Enterprises');
INSERT INTO company_table values( 324, 'CAVE Interactive CO.,LTD.');
INSERT INTO company_table values( 325, 'Gnarled Scar Manipulations');
INSERT INTO company_table values( 326, 'Sebastian Krzyszkowiak');
INSERT INTO company_table values( 327, 'Konrad Burandt');
INSERT INTO company_table values( 328, 'Pawe©© Radej');
INSERT INTO company_table values( 329, 'Joshua Missile');
INSERT INTO company_table values( 330, 'Eleon Game Studios');
INSERT INTO company_table values( 331, 'studiocime');
INSERT INTO company_table values( 332, 'Denneko Yuugi');
INSERT INTO company_table values( 333, 'Giant Squid');
INSERT INTO company_table values( 334, 'Sketchy Logic');
INSERT INTO company_table values( 335, 'Hi-Rez Studios');
INSERT INTO company_table values( 336, 'Clever Endeavour Games');
INSERT INTO company_table values( 337, 'Liz-Arts');
INSERT INTO company_table values( 338, 'Moon Studios GmbH');
INSERT INTO company_table values( 339, 'Axolot Games');
INSERT INTO company_table values( 340, 'Night School Studio');
INSERT INTO company_table values( 341, '1C Company');
INSERT INTO company_table values( 342, 'BANDAI NAMCO Studios Inc.');
INSERT INTO company_table values( 343, 'Tin Man Games');
INSERT INTO company_table values( 344, 'Daniel Mercier');
INSERT INTO company_table values( 345, 'Crystal Dynamics');
INSERT INTO company_table values( 346, 'Tortuga Team');
INSERT INTO company_table values( 347, 'tobyfox');
INSERT INTO company_table values( 348, 'Ezzat Studios');
INSERT INTO company_table values( 349, 'Bloober Team SA');
INSERT INTO company_table values( 350, 'AMPLITUDE Studios');
INSERT INTO company_table values( 351, 'Iceflake Studios');
INSERT INTO company_table values( 352, 'Alawar Stargaze');
INSERT INTO company_table values( 353, 'PixelTail Games');
INSERT INTO company_table values( 354, 'Jesse Makkonen');
INSERT INTO company_table values( 355, 'Shotgun Surgeons');
INSERT INTO company_table values( 356, 'Funcom');
INSERT INTO company_table values( 357, 'PixelFade Inc');
INSERT INTO company_table values( 358, 'ROCKFISH Games');
INSERT INTO company_table values( 359, 'WarGirl Games');
INSERT INTO company_table values( 360, 'DopplerFrog');
INSERT INTO company_table values( 361, 'Abrakam SA');
INSERT INTO company_table values( 362, 'Sylvain Harlaut');
INSERT INTO company_table values( 363, 'Looterkings');
INSERT INTO company_table values( 364, 'Jundroo, LLC');
INSERT INTO company_table values( 365, 'Impressions Games');
INSERT INTO company_table values( 366, 'Mason Lindroth');
INSERT INTO company_table values( 367, 'Fishing Cactus');
INSERT INTO company_table values( 368, 'Trav Nash');
INSERT INTO company_table values( 369, 'Wish Fang');
INSERT INTO company_table values( 370, 'Nerdook Productions');
INSERT INTO company_table values( 371, 'CreSpirit');
INSERT INTO company_table values( 372, 'GemaYue');
INSERT INTO company_table values( 373, 'Running With Scissors');
INSERT INTO company_table values( 374, 'All Seeing Eye Games');
INSERT INTO company_table values( 375, 'Team Eleven Eleven');
INSERT INTO company_table values( 376, 'Glowstick Entertainment');
INSERT INTO company_table values( 377, 'Nathan Meunier');
INSERT INTO company_table values( 378, 'Traveller''s Tales');
INSERT INTO company_table values( 379, 'TT Games');
INSERT INTO company_table values( 380, 'Daniel Mullins Games');
INSERT INTO company_table values( 381, 'Iguana Entertainment');
INSERT INTO company_table values( 382, 'Nightdive Studios');
INSERT INTO company_table values( 383, 'Dominique Grieshofer');
INSERT INTO company_table values( 384, 'Vile Monarch');
INSERT INTO company_table values( 385, 'ebi-hime');
INSERT INTO company_table values( 386, 'Ludosity');
INSERT INTO company_table values( 387, 'Remar Games');
INSERT INTO company_table values( 388, 'StormBrewers');
INSERT INTO company_table values( 389, 'Timushev Vladimir');
INSERT INTO company_table values( 390, 'Composer-Motorin Dmitry (Djinotan)');
INSERT INTO company_table values( 391, 'Charm Games');
INSERT INTO company_table values( 392, 'Soldak Entertainment');
INSERT INTO company_table values( 393, 'Jetdogs Studios');
INSERT INTO company_table values( 394, 'CorePunch Gamestudio');
INSERT INTO company_table values( 395, 'Ithaqua Labs');
INSERT INTO company_table values( 396, 'Technomancy Studios');
INSERT INTO company_table values( 397, 'Sebastian Nigro');
INSERT INTO company_table values( 398, 'Panos Tzimas');
INSERT INTO company_table values( 399, 'Nicolas Bernard');
INSERT INTO company_table values( 400, 'Stormregion');
INSERT INTO company_table values( 401, 'FRENCH-BREAD');
INSERT INTO company_table values( 402, 'Tamsoft');
INSERT INTO company_table values( 403, 'Krome Studios');
INSERT INTO company_table values( 404, 'MAGES. Inc.');
INSERT INTO company_table values( 405, 'ConcernedApe');
INSERT INTO company_table values( 406, 'Spike Chunsoft Co., Ltd.');
INSERT INTO company_table values( 407, 'Abstraction Games');
INSERT INTO company_table values( 408, 'Phr00t''s Software');
INSERT INTO company_table values( 409, 'Cuveet Story');
INSERT INTO company_table values( 410, 'Lached Up Games');
INSERT INTO company_table values( 411, 'John Szymanski');
INSERT INTO company_table values( 412, 'Shawn Hitchcock');
INSERT INTO company_table values( 413, 'Matthew Brown');
INSERT INTO company_table values( 414, 'Tall Tail Studios');
INSERT INTO company_table values( 415, 'Yunus Ayyildiz');
INSERT INTO company_table values( 416, 'Sho Ohhira');
INSERT INTO company_table values( 417, 'Rooster Teeth Games');
INSERT INTO company_table values( 418, 'I-Illusions');
INSERT INTO company_table values( 419, 'Studio 4D');
INSERT INTO company_table values( 420, 'Little Cat Feet');
INSERT INTO company_table values( 421, 'Pilgrim Adventures');
INSERT INTO company_table values( 422, 'GrabTheGames Studios');
INSERT INTO company_table values( 423, 'Isaac Cohen');
INSERT INTO company_table values( 424, 'VaragtP');
INSERT INTO company_table values( 425, 'Hosted Games');
INSERT INTO company_table values( 426, 'Knuckle Cracker');
INSERT INTO company_table values( 427, 'Sorath');
INSERT INTO company_table values( 428, '3Division');
INSERT INTO company_table values( 429, 'SnoutUp');
INSERT INTO company_table values( 430, 'Tarsier Studios');
INSERT INTO company_table values( 431, 'Wube Software LTD.');
INSERT INTO company_table values( 432, 'Square Enix Montr?al');
INSERT INTO company_table values( 433, 'Bombservice');
INSERT INTO company_table values( 434, 'Redshift');
INSERT INTO company_table values( 435, 'GOGII Games');
INSERT INTO company_table values( 436, 'Triangular Pixels');
INSERT INTO company_table values( 437, 'Modern Visual Arts Laboratory');
INSERT INTO company_table values( 438, 'SEO INSEOK');
INSERT INTO company_table values( 439, 'Blacklight Interactive');
INSERT INTO company_table values( 440, '2Chance Projects');
INSERT INTO company_table values( 441, 'IIchan Eroge Team');
INSERT INTO company_table values( 442, 'Monomi Park');
INSERT INTO company_table values( 443, 'Nickervision Studios');
INSERT INTO company_table values( 444, 'Big Corporation');
INSERT INTO company_table values( 445, 'Hunter Studio');
INSERT INTO company_table values( 446, 'Room710Games');
INSERT INTO company_table values( 447, 'Rusty Lake');
INSERT INTO company_table values( 448, 'REL Games');
INSERT INTO company_table values( 449, 'Date Nighto');
INSERT INTO company_table values( 450, 'Adriaan de Jongh');
INSERT INTO company_table values( 451, 'Sylvain Tegroeg');
INSERT INTO company_table values( 452, 'Futuretown');
INSERT INTO company_table values( 453, 'Survios');
INSERT INTO company_table values( 454, 'Innerspace VR');
INSERT INTO company_table values( 455, 'BlackSpot Entertainment');
INSERT INTO company_table values( 456, 'Aldin Dynamics');
INSERT INTO company_table values( 457, 'Pixel Trickery');
INSERT INTO company_table values( 458, 'Sunward Games');
INSERT INTO company_table values( 459, 'Art in Heart');
INSERT INTO company_table values( 460, 'Burak Dabak');
INSERT INTO company_table values( 461, 'Freedomize Studio');
INSERT INTO company_table values( 462, 'Baroque Decay');
INSERT INTO company_table values( 463, 'Wargaming Group Limited');
INSERT INTO company_table values( 464, 'Giants Software');
INSERT INTO company_table values( 465, 'Ubisoft');
INSERT INTO company_table values( 466, 'Sukeban Games');
INSERT INTO company_table values( 467, 'Frontier Developments');
INSERT INTO company_table values( 468, 'Nawia Games');
INSERT INTO company_table values( 469, 'Ghost Town Games Ltd.');
INSERT INTO company_table values( 470, 'Alice & Smith');
INSERT INTO company_table values( 471, 'Thing Trunk');
INSERT INTO company_table values( 472, 'Revival Productions, LLC');
INSERT INTO company_table values( 473, 'Airship Syndicate');
INSERT INTO company_table values( 474, 'Code Horizon');
INSERT INTO company_table values( 475, 'Wevr, Inc.');
INSERT INTO company_table values( 476, 'Trinket Studios');
INSERT INTO company_table values( 477, 'Cygames, Inc.');
INSERT INTO company_table values( 478, 'Brain Seal Ltd');
INSERT INTO company_table values( 479, 'Arif Games');
INSERT INTO company_table values( 480, 'Moltenplay');
INSERT INTO company_table values( 481, '[OneManBand]');
INSERT INTO company_table values( 482, 'xXarabongXx');
INSERT INTO company_table values( 483, 'Rebelephant');
INSERT INTO company_table values( 484, 'TreeFortress Games');
INSERT INTO company_table values( 485, 'Russpuppy');
INSERT INTO company_table values( 486, 'Michaela Laws');
INSERT INTO company_table values( 487, 'Watercress Studios');
INSERT INTO company_table values( 488, 'Ubisoft Paris');
INSERT INTO company_table values( 489, 'Ubisoft Annecy');
INSERT INTO company_table values( 490, 'Ubisoft Bucharest');
INSERT INTO company_table values( 491, 'Ubisoft Montpellier');
INSERT INTO company_table values( 492, 'Ubisoft Milan');
INSERT INTO company_table values( 493, 'Reflections');
INSERT INTO company_table values( 494, 'Hexecutable');
INSERT INTO company_table values( 495, 'Chandler Rounsley');
INSERT INTO company_table values( 496, 'Michal Pawlowski');
INSERT INTO company_table values( 497, 'Zetsubou');
INSERT INTO company_table values( 498, 'Lapovich');
INSERT INTO company_table values( 499, 'InterOne Inc.');
INSERT INTO company_table values( 500, 'Zach Tsiakalis-Brown');
INSERT INTO company_table values( 501, 'George Eracleous');
INSERT INTO company_table values( 502, 'Errol Bucy');
INSERT INTO company_table values( 503, 'YETU GAME');
INSERT INTO company_table values( 504, 'Out of the Park Developments');
INSERT INTO company_table values( 505, '?â©ÍïíÂãø');
INSERT INTO company_table values( 506, 'Vladimir Maslov');
INSERT INTO company_table values( 507, 'Kyrylo Kuzyk');
INSERT INTO company_table values( 508, 'TPP Studio');
INSERT INTO company_table values( 509, 'Big Cow Studios');
INSERT INTO company_table values( 510, 'takk');
INSERT INTO company_table values( 511, 'Against Gravity¢ç');
INSERT INTO company_table values( 512, 'DreaMory');
INSERT INTO company_table values( 513, 'bad chalk');
INSERT INTO company_table values( 514, 'Manuel Pazos');
INSERT INTO company_table values( 515, 'Daniel Celem?n');
INSERT INTO company_table values( 516, 'Nerial');
INSERT INTO company_table values( 517, 'Arzola''s');
INSERT INTO company_table values( 518, 'CloudGate Studio, Inc.');
INSERT INTO company_table values( 519, 'Nippon Ichi Software, Inc.');
INSERT INTO company_table values( 520, 'ClickGames');
INSERT INTO company_table values( 521, 'sen');
INSERT INTO company_table values( 522, 'ZOV GAME STUDIO');
INSERT INTO company_table values( 523, 'K Bros Games');
INSERT INTO company_table values( 524, 'Might and Delight');
INSERT INTO company_table values( 525, 'Halfbrick Studios Pty Ltd');
INSERT INTO company_table values( 526, 'For Fun Labs');
INSERT INTO company_table values( 527, 'Vifth Floor');
INSERT INTO company_table values( 528, 'Billy Goat Entertainment Ltd');
INSERT INTO company_table values( 529, 'The Secret Location');
INSERT INTO company_table values( 530, 'Red Matter Studio');
INSERT INTO company_table values( 531, 'Realmforge Studios');
INSERT INTO company_table values( 532, 'Blue Giraffe');
INSERT INTO company_table values( 533, 'hOSHI');
INSERT INTO company_table values( 534, 'Michal Kruba');
INSERT INTO company_table values( 535, 'JCKSLAP');
INSERT INTO company_table values( 536, 'Pavel Jamal');
INSERT INTO company_table values( 537, 'Noio');
INSERT INTO company_table values( 538, 'Somi');
INSERT INTO company_table values( 539, 'BigCheeseGames');
INSERT INTO company_table values( 540, 'Rabbiton');
INSERT INTO company_table values( 541, 'HA Studio Ltd.');
INSERT INTO company_table values( 542, 'Giant Sparrow');
INSERT INTO company_table values( 543, 'Midnight Party');
INSERT INTO company_table values( 544, 'Aleksandr Golovkin');
INSERT INTO company_table values( 545, 'Sierra');
INSERT INTO company_table values( 546, 'Cartboard Games');
INSERT INTO company_table values( 547, 'COLOPL, Inc.');
INSERT INTO company_table values( 548, 'Jutsu Games');
INSERT INTO company_table values( 549, 'Stress Level Zero');
INSERT INTO company_table values( 550, 'Nova-box');
INSERT INTO company_table values( 551, 'OperaHouse Corporation');
INSERT INTO company_table values( 552, 'Scott Lowe');
INSERT INTO company_table values( 553, 'Philipp Lenssen');
INSERT INTO company_table values( 554, 'Ludomotion');
INSERT INTO company_table values( 555, 'Hostel Games');
INSERT INTO company_table values( 556, 'Blastoid Entertainment');
INSERT INTO company_table values( 557, 'SVRVIVE Studios');
INSERT INTO company_table values( 558, 'RLTY CHK');
INSERT INTO company_table values( 559, 'Dragon Whisper Game');
INSERT INTO company_table values( 560, 'Marvelous Inc.');
INSERT INTO company_table values( 561, 'ùë?ÐôÎ¡Ðü');
INSERT INTO company_table values( 562, 'Home Net Games');
INSERT INTO company_table values( 563, 'Matt Dabrowski');
INSERT INTO company_table values( 564, 'Codemasters');
INSERT INTO company_table values( 565, 'Enigmatic');
INSERT INTO company_table values( 566, 'Toast');
INSERT INTO company_table values( 567, 'From The Bard');
INSERT INTO company_table values( 568, 'ProGames Studio');
INSERT INTO company_table values( 569, 'Brian Lindenhof');
INSERT INTO company_table values( 570, 'batensan');
INSERT INTO company_table values( 571, 'DIVR Labs');
INSERT INTO company_table values( 572, 'CFK Co., Ltd.');
INSERT INTO company_table values( 573, 'Kyle Seeley');
INSERT INTO company_table values( 574, 'Spicy Tails');
INSERT INTO company_table values( 575, 'The Munky');
INSERT INTO company_table values( 576, 'Taylor Stapleton');
INSERT INTO company_table values( 577, 'Three Fields Entertainment');
INSERT INTO company_table values( 578, 'Quiet River');
INSERT INTO company_table values( 579, 'Sirius Sam');
INSERT INTO company_table values( 580, 'Runner Duck');
INSERT INTO company_table values( 581, 'Owlet');
INSERT INTO company_table values( 582, 'nDreams / Near Light');
INSERT INTO company_table values( 583, 'Pillow Fight');
INSERT INTO company_table values( 584, 'GameHouse');
INSERT INTO company_table values( 585, 'NS STUDIO');
INSERT INTO company_table values( 586, 'Tricol Co., Ltd.');
INSERT INTO company_table values( 587, 'Sourcenity GmbH');
INSERT INTO company_table values( 588, 'Square Enix');
INSERT INTO company_table values( 589, 'FantaBlade Network');
INSERT INTO company_table values( 590, '10Ants Hill');
INSERT INTO company_table values( 591, 'Chris Chung');
INSERT INTO company_table values( 592, 'Fifth One');
INSERT INTO company_table values( 593, 'Game Science');
INSERT INTO company_table values( 594, 'Barrel Roll Games');
INSERT INTO company_table values( 595, 'Construct Studio');
INSERT INTO company_table values( 596, 'Kitsune Games');
INSERT INTO company_table values( 597, 'Battlecruiser Games');
INSERT INTO company_table values( 598, 'Falcoware');
INSERT INTO company_table values( 599, 'btf GmbH');
INSERT INTO company_table values( 600, 'Circus Atos');
INSERT INTO company_table values( 601, 'Zoom Out Games');
INSERT INTO company_table values( 602, 'Project Moon');
INSERT INTO company_table values( 603, 'Dicesuki');
INSERT INTO company_table values( 604, 'Lion Shield, LLC');
INSERT INTO company_table values( 605, 'Tyler Hurd');
INSERT INTO company_table values( 606, 'Team Nekojishi');
INSERT INTO company_table values( 607, 'SNK CORPORATION');
INSERT INTO company_table values( 608, 'MyDearest');
INSERT INTO company_table values( 609, 'storyk21674');
INSERT INTO company_table values( 610, 'STILILA');
INSERT INTO company_table values( 611, '?Ó±');
INSERT INTO company_table values( 612, 'LaboRatStudio');
INSERT INTO company_table values( 613, 'Funghisoft');
INSERT INTO company_table values( 614, 'rebel rabbit');
INSERT INTO company_table values( 615, 'Prideful Sloth');
INSERT INTO company_table values( 616, 'StevenHarmonGames');
INSERT INTO company_table values( 617, 'Broken Rules');
INSERT INTO company_table values( 618, 'Ran');
INSERT INTO company_table values( 619, 'Huge Robot');
INSERT INTO company_table values( 620, '22cans');
INSERT INTO company_table values( 621, 'Christian Whitehead');
INSERT INTO company_table values( 622, 'Headcannon');
INSERT INTO company_table values( 623, 'PagodaWest Games');
INSERT INTO company_table values( 624, 'Overflow');
INSERT INTO company_table values( 625, 'Abigail Corfman');
INSERT INTO company_table values( 626, 'Ebullience Games');
INSERT INTO company_table values( 627, '4D Door Games');
INSERT INTO company_table values( 628, 'BekkerDev Studio');
INSERT INTO company_table values( 629, 'Motion Twin');
INSERT INTO company_table values( 630, 'Dr_Crewcut');
INSERT INTO company_table values( 631, 'White Door Games');
INSERT INTO company_table values( 632, 'Anvil Game Studios');
INSERT INTO company_table values( 633, 'Systemic Games');
INSERT INTO company_table values( 634, 'Konami Digital Entertainment Co., Ltd.');
INSERT INTO company_table values( 635, 'The Gentlebros');
INSERT INTO company_table values( 636, 'Doborog Games');
INSERT INTO company_table values( 637, 'Asymmetric');
INSERT INTO company_table values( 638, 'Kremlingames');
INSERT INTO company_table values( 639, '10kbit Games');
INSERT INTO company_table values( 640, 'Elven Workshop');
INSERT INTO company_table values( 641, 'Eternal Night Studios');
INSERT INTO company_table values( 642, 'AQURIA');
INSERT INTO company_table values( 643, 'Nordic Trolls');
INSERT INTO company_table values( 644, 'Baba Yaga Games');
INSERT INTO company_table values( 645, 'Tree Men Games');
INSERT INTO company_table values( 646, 'Surreal Games');
INSERT INTO company_table values( 647, 'Paleno Games');
INSERT INTO company_table values( 648, 'Jake Hollands');
INSERT INTO company_table values( 649, 'Salvation');
INSERT INTO company_table values( 650, 'Emanon Studios');
INSERT INTO company_table values( 651, 'What Pumpkin Games, Inc.');
INSERT INTO company_table values( 652, 'Sports Interactive');
INSERT INTO company_table values( 653, 'Play:D');
INSERT INTO company_table values( 654, 'Blender Games');
INSERT INTO company_table values( 655, 'DIGIDICED');
INSERT INTO company_table values( 656, 'KOGADO STUDIO');
INSERT INTO company_table values( 657, 'ZuoBuLaiGame');
INSERT INTO company_table values( 658, 'LunarPixel');
INSERT INTO company_table values( 659, 'Alysson Moraes');
INSERT INTO company_table values( 660, 'Creability');
INSERT INTO company_table values( 661, 'Secret Level SRL');
INSERT INTO company_table values( 662, 'Alexey Glinskiy');
INSERT INTO company_table values( 663, 'ÔòÎÃêý?');
INSERT INTO company_table values( 664, 'Red Dot Games');
INSERT INTO company_table values( 665, 'YarGri');
INSERT INTO company_table values( 666, 'Lighthouse Games Studio');
INSERT INTO company_table values( 667, 'Apoapsis Studios');
INSERT INTO company_table values( 668, 'Catobyte');
INSERT INTO company_table values( 669, 'Landfall West');
INSERT INTO company_table values( 670, 'Ninja Kiwi');
INSERT INTO company_table values( 671, 'Nifflas Games');
INSERT INTO company_table values( 672, 'Thalasse Games');
INSERT INTO company_table values( 673, 'DoubleMoose Games');
INSERT INTO company_table values( 674, 'Camex Games');
INSERT INTO company_table values( 675, 'Igor Rashkuev');
INSERT INTO company_table values( 676, 'PuzzleRoo');
INSERT INTO company_table values( 677, 'GrizzlyGames');
INSERT INTO company_table values( 678, 'Sixteen Tons Entertainment');
INSERT INTO company_table values( 679, 'ß¾ú­«¢«ê«¹ü³äÅ?');
SET DEFINE ON;
