SET DEFINE OFF;
INSERT	INTO	Language_table		VALUES(			1,			'Portuguese-Brazil'	)
INSERT	INTO	Language_table		VALUES(			2,			'Italian'	)
INSERT	INTO	Language_table		VALUES(			3,			'Russian'	)
INSERT	INTO	Language_table		VALUES(			4,			'German'	)
INSERT	INTO	Language_table		VALUES(			5,			'Swedish'	)
INSERT	INTO	Language_table		VALUES(			6,			'Turkish'	)
INSERT	INTO	Language_table		VALUES(			7,			'Ukrainian'	)
INSERT	INTO	Language_table		VALUES(			8,			'French'	)
INSERT	INTO	Language_table		VALUES(			9,			'Portuguese'	)
INSERT	INTO	Language_table		VALUES(			10,			'Finnish'	)
INSERT	INTO	Language_table		VALUES(			11,			'Spanish'	)
INSERT	INTO	Language_table		VALUES(			12,			'Thai'	)
INSERT	INTO	Language_table		VALUES(			13,			'Norwegian'	)
INSERT	INTO	Language_table		VALUES(			14,			'Simplified Chinese'	)
INSERT	INTO	Language_table		VALUES(			15,			'Polish'	)
INSERT	INTO	Language_table		VALUES(			16,			'Romanian'	)
INSERT	INTO	Language_table		VALUES(			17,			'Korean'	)
INSERT	INTO	Language_table		VALUES(			18,			'Bulgarian'	)
INSERT	INTO	Language_table		VALUES(			19,			'Japanese'	)
INSERT	INTO	Language_table		VALUES(			20,			'English'	)
INSERT	INTO	Language_table		VALUES(			21,			'Danish'	)
INSERT	INTO	Language_table		VALUES(			22,			'Czech'	)
INSERT	INTO	Language_table		VALUES(			23,			'Hungarian'	)
INSERT	INTO	Language_table		VALUES(			24,			'Dutch'	)
INSERT	INTO	Language_table		VALUES(			25,			'Greek'	)
INSERT	INTO	Language_table		VALUES(			26,			'Traditional Chinese'	)
INSERT	INTO	Language_table		VALUES(			27,			'Arabic'	)
SET DEFINE ON;
