SET DEFINE OFF;
INSERT		INTO	Tag_Table			VALUES (				4608,			'Swordplay'		);
INSERT		INTO	Tag_Table			VALUES (				1027,			'Audio Production'		);
INSERT		INTO	Tag_Table			VALUES (				5125,			'Procedural Generation'		);
INSERT		INTO	Tag_Table			VALUES (				17927,			'Pool'		);
INSERT		INTO	Tag_Table			VALUES (				9,			'Strategy'		);
INSERT		INTO	Tag_Table			VALUES (				4106,			'Action-Adventure'		);
INSERT		INTO	Tag_Table			VALUES (				1036,			'Education'		);
INSERT		INTO	Tag_Table			VALUES (				1038,			'Web Publishing'		);
INSERT		INTO	Tag_Table			VALUES (				21006,			'Underground'		);
INSERT		INTO	Tag_Table			VALUES (				19,			'Action'		);
INSERT		INTO	Tag_Table			VALUES (				4115,			'Cyberpunk'		);
INSERT		INTO	Tag_Table			VALUES (				21,			'Adventure'		);
INSERT		INTO	Tag_Table			VALUES (				19995,			'Dark Comedy'		);
INSERT		INTO	Tag_Table			VALUES (				4637,			'Top-Down Shooter'		);
INSERT		INTO	Tag_Table			VALUES (				5153,			'Kickstarter'		);
INSERT		INTO	Tag_Table			VALUES (				5154,			'Score Attack'		);
INSERT		INTO	Tag_Table			VALUES (				6691,			'1990''s'		);
INSERT		INTO	Tag_Table			VALUES (				4136,			'Funny'		);
INSERT		INTO	Tag_Table			VALUES (				5160,			'Dinosaurs'		);
INSERT		INTO	Tag_Table			VALUES (				7208,			'Female Protagonist'		);
INSERT		INTO	Tag_Table			VALUES (				4137,			'Transhumanism'		);
INSERT		INTO	Tag_Table			VALUES (				5673,			'Modern'		);
INSERT		INTO	Tag_Table			VALUES (				31275,			'Text-Based'		);
INSERT		INTO	Tag_Table			VALUES (				6702,			'Mars'		);
INSERT		INTO	Tag_Table			VALUES (				4145,			'Cinematic'		);
INSERT		INTO	Tag_Table			VALUES (				4150,			'World War II'		);
INSERT		INTO	Tag_Table			VALUES (				9271,			'Trading Card Game'		);
INSERT		INTO	Tag_Table			VALUES (				10808,			'Supernatural'		);
INSERT		INTO	Tag_Table			VALUES (				7226,			'Football'		);
INSERT		INTO	Tag_Table			VALUES (				14906,			'Intentionally Awkward Controls'		);
INSERT		INTO	Tag_Table			VALUES (				4155,			'Class-Based'		);
INSERT		INTO	Tag_Table			VALUES (				4667,			'Violent'		);
INSERT		INTO	Tag_Table			VALUES (				5179,			'Cold War'		);
INSERT		INTO	Tag_Table			VALUES (				8253,			'Music-Based Procedural Generation'		);
INSERT		INTO	Tag_Table			VALUES (				4158,			'Beat ''em up'		);
INSERT		INTO	Tag_Table			VALUES (				7743,			'1980s'		);
INSERT		INTO	Tag_Table			VALUES (				10816,			'Split Screen'		);
INSERT		INTO	Tag_Table			VALUES (				4161,			'Real-Time'		);
INSERT		INTO	Tag_Table			VALUES (				5186,			'Psychological'		);
INSERT		INTO	Tag_Table			VALUES (				379975,			'Clicker'		);
INSERT		INTO	Tag_Table			VALUES (				11333,			'Villain Protagonist'		);
INSERT		INTO	Tag_Table			VALUES (				4166,			'Atmospheric'		);
INSERT		INTO	Tag_Table			VALUES (				4168,			'Military'		);
INSERT		INTO	Tag_Table			VALUES (				6730,			'PvE'		);
INSERT		INTO	Tag_Table			VALUES (				22602,			'Agriculture'		);
INSERT		INTO	Tag_Table			VALUES (				4172,			'Medieval'		);
INSERT		INTO	Tag_Table			VALUES (				4684,			'Wargame'		);
INSERT		INTO	Tag_Table			VALUES (				5708,			'Remake'		);
INSERT		INTO	Tag_Table			VALUES (				4175,			'Realistic'		);
INSERT		INTO	Tag_Table			VALUES (				5711,			'Team-Based'		);
INSERT		INTO	Tag_Table			VALUES (				1616,			'Trains'		);
INSERT		INTO	Tag_Table			VALUES (				7250,			'Linear'		);
INSERT		INTO	Tag_Table			VALUES (				13906,			'Game Development'		);
INSERT		INTO	Tag_Table			VALUES (				15954,			'Silent Protagonist'		);
INSERT		INTO	Tag_Table			VALUES (				84,			'Design & Illustration'		);
INSERT		INTO	Tag_Table			VALUES (				5716,			'Mystery'		);
INSERT		INTO	Tag_Table			VALUES (				597,			'Casual'		);
INSERT		INTO	Tag_Table			VALUES (				1621,			'Music'		);
INSERT		INTO	Tag_Table			VALUES (				4182,			'Singleplayer'		);
INSERT		INTO	Tag_Table			VALUES (				87,			'Utilities'		);
INSERT		INTO	Tag_Table			VALUES (				599,			'Simulation'		);
INSERT		INTO	Tag_Table			VALUES (				4695,			'Economy'		);
INSERT		INTO	Tag_Table			VALUES (				4184,			'Chess'		);
INSERT		INTO	Tag_Table			VALUES (				1625,			'Platformer'		);
INSERT		INTO	Tag_Table			VALUES (				1628,			'Metroidvania'		);
INSERT		INTO	Tag_Table			VALUES (				4700,			'Movie'		);
INSERT		INTO	Tag_Table			VALUES (				150626,			'Gaming'		);
INSERT		INTO	Tag_Table			VALUES (				4195,			'Cartoony'		);
INSERT		INTO	Tag_Table			VALUES (				7782,			'Cult Classic'		);
INSERT		INTO	Tag_Table			VALUES (				4711,			'Replay Value'		);
INSERT		INTO	Tag_Table			VALUES (				4202,			'Trading'		);
INSERT		INTO	Tag_Table			VALUES (				51306,			'Foreign'		);
INSERT		INTO	Tag_Table			VALUES (				1643,			'Building'		);
INSERT		INTO	Tag_Table			VALUES (				1644,			'Driving'		);
INSERT		INTO	Tag_Table			VALUES (				5228,			'Blood'		);
INSERT		INTO	Tag_Table			VALUES (				1645,			'Tower Defense'		);
INSERT		INTO	Tag_Table			VALUES (				1646,			'Hack and Slash'		);
INSERT		INTO	Tag_Table			VALUES (				27758,			'Voice Control'		);
INSERT		INTO	Tag_Table			VALUES (				1647,			'Western'		);
INSERT		INTO	Tag_Table			VALUES (				19568,			'Cycling'		);
INSERT		INTO	Tag_Table			VALUES (				113,			'Free to Play'		);
INSERT		INTO	Tag_Table			VALUES (				1649,			'GameMaker'		);
INSERT		INTO	Tag_Table			VALUES (				1651,			'Satire'		);
INSERT		INTO	Tag_Table			VALUES (				1654,			'Relaxing'		);
INSERT		INTO	Tag_Table			VALUES (				4726,			'Cute'		);
INSERT		INTO	Tag_Table			VALUES (				17015,			'Werewolves'		);
INSERT		INTO	Tag_Table			VALUES (				5752,			'Robots'		);
INSERT		INTO	Tag_Table			VALUES (				122,			'RPG'		);
INSERT		INTO	Tag_Table			VALUES (				1659,			'Zombies'		);
INSERT		INTO	Tag_Table			VALUES (				1662,			'Survival'		);
INSERT		INTO	Tag_Table			VALUES (				1663,			'FPS'		);
INSERT		INTO	Tag_Table			VALUES (				128,			'Massively Multiplayer'		);
INSERT		INTO	Tag_Table			VALUES (				1664,			'Puzzle'		);
INSERT		INTO	Tag_Table			VALUES (				4736,			'2D Fighter'		);
INSERT		INTO	Tag_Table			VALUES (				1665,			'Match 3'		);
INSERT		INTO	Tag_Table			VALUES (				1666,			'Card Game'		);
INSERT		INTO	Tag_Table			VALUES (				1667,			'Horror'		);
INSERT		INTO	Tag_Table			VALUES (				6276,			'Inventory Management'		);
INSERT		INTO	Tag_Table			VALUES (				1669,			'Moddable'		);
INSERT		INTO	Tag_Table			VALUES (				5765,			'Gun Customization'		);
INSERT		INTO	Tag_Table			VALUES (				1670,			'4X'		);
INSERT		INTO	Tag_Table			VALUES (				1671,			'Superhero'		);
INSERT		INTO	Tag_Table			VALUES (				4231,			'Action RPG'		);
INSERT		INTO	Tag_Table			VALUES (				1673,			'Aliens'		);
INSERT		INTO	Tag_Table			VALUES (				1674,			'Typing'		);
INSERT		INTO	Tag_Table			VALUES (				4234,			'Short'		);
INSERT		INTO	Tag_Table			VALUES (				4747,			'Character Customization'		);
INSERT		INTO	Tag_Table			VALUES (				1676,			'RTS'		);
INSERT		INTO	Tag_Table			VALUES (				4236,			'Loot'		);
INSERT		INTO	Tag_Table			VALUES (				1677,			'Turn-Based'		);
INSERT		INTO	Tag_Table			VALUES (				1678,			'War'		);
INSERT		INTO	Tag_Table			VALUES (				1679,			'Soccer'		);
INSERT		INTO	Tag_Table			VALUES (				1680,			'Heist'		);
INSERT		INTO	Tag_Table			VALUES (				1681,			'Pirates'		);
INSERT		INTO	Tag_Table			VALUES (				4242,			'Episodic'		);
INSERT		INTO	Tag_Table			VALUES (				4754,			'Politics'		);
INSERT		INTO	Tag_Table			VALUES (				180368,			'Faith'		);
INSERT		INTO	Tag_Table			VALUES (				1684,			'Fantasy'		);
INSERT		INTO	Tag_Table			VALUES (				1685,			'Co-op'		);
INSERT		INTO	Tag_Table			VALUES (				4758,			'Twin Stick Shooter'		);
INSERT		INTO	Tag_Table			VALUES (				1687,			'Stealth'		);
INSERT		INTO	Tag_Table			VALUES (				1688,			'Ninja'		);
INSERT		INTO	Tag_Table			VALUES (				4252,			'Stylized'		);
INSERT		INTO	Tag_Table			VALUES (				1693,			'Classic'		);
INSERT		INTO	Tag_Table			VALUES (				10397,			'Memes'		);
INSERT		INTO	Tag_Table			VALUES (				1694,			'Batman'		);
INSERT		INTO	Tag_Table			VALUES (				1695,			'Open World'		);
INSERT		INTO	Tag_Table			VALUES (				4255,			'Shoot ''Em Up'		);
INSERT		INTO	Tag_Table			VALUES (				6815,			'Hand-drawn'		);
INSERT		INTO	Tag_Table			VALUES (				7328,			'Bowling'		);
INSERT		INTO	Tag_Table			VALUES (				1697,			'Third Person'		);
INSERT		INTO	Tag_Table			VALUES (				1698,			'Point & Click'		);
INSERT		INTO	Tag_Table			VALUES (				5794,			'Science'		);
INSERT		INTO	Tag_Table			VALUES (				18594,			'FMV'		);
INSERT		INTO	Tag_Table			VALUES (				5796,			'Bullet Time'		);
INSERT		INTO	Tag_Table			VALUES (				7332,			'Base Building'		);
INSERT		INTO	Tag_Table			VALUES (				1702,			'Crafting'		);
INSERT		INTO	Tag_Table			VALUES (				6310,			'Diplomacy'		);
INSERT		INTO	Tag_Table			VALUES (				603297,			'Hardware'		);
INSERT		INTO	Tag_Table			VALUES (				4777,			'Spectacle fighter'		);
INSERT		INTO	Tag_Table			VALUES (				1708,			'Tactical'		);
INSERT		INTO	Tag_Table			VALUES (				1710,			'Surreal'		);
INSERT		INTO	Tag_Table			VALUES (				134316,			'Philisophical'		);
INSERT		INTO	Tag_Table			VALUES (				8369,			'Investigation'		);
INSERT		INTO	Tag_Table			VALUES (				1714,			'Psychedelic'		);
INSERT		INTO	Tag_Table			VALUES (				29363,			'3D Vision'		);
INSERT		INTO	Tag_Table			VALUES (				1716,			'Rogue-like'		);
INSERT		INTO	Tag_Table			VALUES (				5300,			'God Game'		);
INSERT		INTO	Tag_Table			VALUES (				1717,			'Hex Grid'		);
INSERT		INTO	Tag_Table			VALUES (				1718,			'MOBA'		);
INSERT		INTO	Tag_Table			VALUES (				1719,			'Comedy'		);
INSERT		INTO	Tag_Table			VALUES (				4791,			'Top-Down'		);
INSERT		INTO	Tag_Table			VALUES (				1720,			'Dungeon Crawler'		);
INSERT		INTO	Tag_Table			VALUES (				12472,			'Management'		);
INSERT		INTO	Tag_Table			VALUES (				1721,			'Psychological Horror'		);
INSERT		INTO	Tag_Table			VALUES (				699,			'Racing'		);
INSERT		INTO	Tag_Table			VALUES (				701,			'Sports'		);
INSERT		INTO	Tag_Table			VALUES (				5310,			'Games Workshop'		);
INSERT		INTO	Tag_Table			VALUES (				1730,			'Sokoban'		);
INSERT		INTO	Tag_Table			VALUES (				1732,			'Voxel'		);
INSERT		INTO	Tag_Table			VALUES (				15045,			'Flight'		);
INSERT		INTO	Tag_Table			VALUES (				1734,			'Fast-Paced'		);
INSERT		INTO	Tag_Table			VALUES (				1735,			'Star Wars'		);
INSERT		INTO	Tag_Table			VALUES (				4295,			'Futuristic'		);
INSERT		INTO	Tag_Table			VALUES (				1736,			'LEGO'		);
INSERT		INTO	Tag_Table			VALUES (				7368,			'Local Multiplayer'		);
INSERT		INTO	Tag_Table			VALUES (				1738,			'Hidden Object'		);
INSERT		INTO	Tag_Table			VALUES (				15564,			'Fishing'		);
INSERT		INTO	Tag_Table			VALUES (				1741,			'Turn-Based Strategy'		);
INSERT		INTO	Tag_Table			VALUES (				1742,			'Story Rich'		);
INSERT		INTO	Tag_Table			VALUES (				1743,			'Fighting'		);
INSERT		INTO	Tag_Table			VALUES (				4305,			'Colorful'		);
INSERT		INTO	Tag_Table			VALUES (				1746,			'Basketball'		);
INSERT		INTO	Tag_Table			VALUES (				47827,			'Wrestling'		);
INSERT		INTO	Tag_Table			VALUES (				3796,			'Based On A Novel'		);
INSERT		INTO	Tag_Table			VALUES (				4821,			'Mechs'		);
INSERT		INTO	Tag_Table			VALUES (				6869,			'Nonlinear'		);
INSERT		INTO	Tag_Table			VALUES (				3798,			'Side Scroller'		);
INSERT		INTO	Tag_Table			VALUES (				16598,			'Space Sim'		);
INSERT		INTO	Tag_Table			VALUES (				1751,			'Comic Book'		);
INSERT		INTO	Tag_Table			VALUES (				3799,			'Visual Novel'		);
INSERT		INTO	Tag_Table			VALUES (				1752,			'Rhythm'		);
INSERT		INTO	Tag_Table			VALUES (				1754,			'MMORPG'		);
INSERT		INTO	Tag_Table			VALUES (				21722,			'Lara Croft'		);
INSERT		INTO	Tag_Table			VALUES (				1755,			'Space'		);
INSERT		INTO	Tag_Table			VALUES (				5851,			'Isometric'		);
INSERT		INTO	Tag_Table			VALUES (				1756,			'Great Soundtrack'		);
INSERT		INTO	Tag_Table			VALUES (				71389,			'Spelling'		);
INSERT		INTO	Tag_Table			VALUES (				21725,			'Tactical RPG'		);
INSERT		INTO	Tag_Table			VALUES (				16094,			'Mythology'		);
INSERT		INTO	Tag_Table			VALUES (				1759,			'Perma Death'		);
INSERT		INTO	Tag_Table			VALUES (				3810,			'Sandbox'		);
INSERT		INTO	Tag_Table			VALUES (				4835,			'6DOF'		);
INSERT		INTO	Tag_Table			VALUES (				5348,			'Mod'		);
INSERT		INTO	Tag_Table			VALUES (				3813,			'Real Time Tactics'		);
INSERT		INTO	Tag_Table			VALUES (				4325,			'Turn-Based Combat'		);
INSERT		INTO	Tag_Table			VALUES (				3814,			'Third-Person Shooter'		);
INSERT		INTO	Tag_Table			VALUES (				5350,			'Family Friendly'		);
INSERT		INTO	Tag_Table			VALUES (				4328,			'City Builder'		);
INSERT		INTO	Tag_Table			VALUES (				4840,			'4 Player Local'		);
INSERT		INTO	Tag_Table			VALUES (				1770,			'Board Game'		);
INSERT		INTO	Tag_Table			VALUES (				6378,			'Crime'		);
INSERT		INTO	Tag_Table			VALUES (				1773,			'Arcade'		);
INSERT		INTO	Tag_Table			VALUES (				4845,			'Capitalism'		);
INSERT		INTO	Tag_Table			VALUES (				1774,			'Shooter'		);
INSERT		INTO	Tag_Table			VALUES (				1775,			'PvP'		);
INSERT		INTO	Tag_Table			VALUES (				1777,			'Steampunk'		);
INSERT		INTO	Tag_Table			VALUES (				8945,			'Resource Management'		);
INSERT		INTO	Tag_Table			VALUES (				5363,			'Destruction'		);
INSERT		INTO	Tag_Table			VALUES (				4853,			'Political'		);
INSERT		INTO	Tag_Table			VALUES (				4342,			'Dark'		);
INSERT		INTO	Tag_Table			VALUES (				7926,			'Artificial Intelligence'		);
INSERT		INTO	Tag_Table			VALUES (				4345,			'Gore'		);
INSERT		INTO	Tag_Table			VALUES (				3834,			'Exploration'		);
INSERT		INTO	Tag_Table			VALUES (				3835,			'Post-apocalyptic'		);
INSERT		INTO	Tag_Table			VALUES (				5372,			'Conspiracy'		);
INSERT		INTO	Tag_Table			VALUES (				6910,			'Naval'		);
INSERT		INTO	Tag_Table			VALUES (				3839,			'First-Person'		);
INSERT		INTO	Tag_Table			VALUES (				7423,			'Sniper'		);
INSERT		INTO	Tag_Table			VALUES (				348922,			'Steam Machine'		);
INSERT		INTO	Tag_Table			VALUES (				3841,			'Local Co-Op'		);
INSERT		INTO	Tag_Table			VALUES (				3843,			'Online Co-Op'		);
INSERT		INTO	Tag_Table			VALUES (				6915,			'Martial Arts'		);
INSERT		INTO	Tag_Table			VALUES (				5382,			'World War I'		);
INSERT		INTO	Tag_Table			VALUES (				11014,			'Interactive Fiction'		);
INSERT		INTO	Tag_Table			VALUES (				7432,			'Lovecraftian'		);
INSERT		INTO	Tag_Table			VALUES (				13577,			'Sailing'		);
INSERT		INTO	Tag_Table			VALUES (				9994,			'Experience'		);
INSERT		INTO	Tag_Table			VALUES (				4364,			'Grand Strategy'		);
INSERT		INTO	Tag_Table			VALUES (				5900,			'Walking Simulator'		);
INSERT		INTO	Tag_Table			VALUES (				7948,			'Soundtrack'		);
INSERT		INTO	Tag_Table			VALUES (				3854,			'Lore-Rich'		);
INSERT		INTO	Tag_Table			VALUES (				4878,			'Parody '		);
INSERT		INTO	Tag_Table			VALUES (				5390,			'Time Attack'		);
INSERT		INTO	Tag_Table			VALUES (				784,			'Video Production'		);
INSERT		INTO	Tag_Table			VALUES (				3859,			'Multiplayer'		);
INSERT		INTO	Tag_Table			VALUES (				5395,			'3D Platformer'		);
INSERT		INTO	Tag_Table			VALUES (				4885,			'Bullet Hell'		);
INSERT		INTO	Tag_Table			VALUES (				4376,			'Assassin'		);
INSERT		INTO	Tag_Table			VALUES (				12057,			'Tutorial'		);
INSERT		INTO	Tag_Table			VALUES (				6426,			'Choices Matter'		);
INSERT		INTO	Tag_Table			VALUES (				3871,			'2D'		);
INSERT		INTO	Tag_Table			VALUES (				5407,			'Benchmark'		);
INSERT		INTO	Tag_Table			VALUES (				5923,			'Dark Humor'		);
INSERT		INTO	Tag_Table			VALUES (				6948,			'Rome'		);
INSERT		INTO	Tag_Table			VALUES (				3878,			'Competitive'		);
INSERT		INTO	Tag_Table			VALUES (				809,			'Photo Editing'		);
INSERT		INTO	Tag_Table			VALUES (				4400,			'Abstract'		);
INSERT		INTO	Tag_Table			VALUES (				7478,			'Illuminati'		);
INSERT		INTO	Tag_Table			VALUES (				5432,			'Programming'		);
INSERT		INTO	Tag_Table			VALUES (				7481,			'Controller'		);
INSERT		INTO	Tag_Table			VALUES (				6971,			'Multiple Endings'		);
INSERT		INTO	Tag_Table			VALUES (				14139,			'Turn-Based Tactics'		);
INSERT		INTO	Tag_Table			VALUES (				12095,			'Sexual Content'		);
INSERT		INTO	Tag_Table			VALUES (				15172,			'Conversation'		);
INSERT		INTO	Tag_Table			VALUES (				9541,			'Demons'		);
INSERT		INTO	Tag_Table			VALUES (				24904,			'NSFW'		);
INSERT		INTO	Tag_Table			VALUES (				8013,			'Software'		);
INSERT		INTO	Tag_Table			VALUES (				9551,			'Dating Sim'		);
INSERT		INTO	Tag_Table			VALUES (				4434,			'JRPG'		);
INSERT		INTO	Tag_Table			VALUES (				4947,			'Romance'		);
INSERT		INTO	Tag_Table			VALUES (				31579,			'Otome'		);
INSERT		INTO	Tag_Table			VALUES (				9564,			'Hunting'		);
INSERT		INTO	Tag_Table			VALUES (				5981,			'Mining'		);
INSERT		INTO	Tag_Table			VALUES (				5984,			'Drama'		);
INSERT		INTO	Tag_Table			VALUES (				233824,			'Feature Film'		);
INSERT		INTO	Tag_Table			VALUES (				3942,			'Sci-fi'		);
INSERT		INTO	Tag_Table			VALUES (				872,			'Animation & Modeling'		);
INSERT		INTO	Tag_Table			VALUES (				17770,			'Asynchronous Multiplayer'		);
INSERT		INTO	Tag_Table			VALUES (				4975,			'2.5D'		);
INSERT		INTO	Tag_Table			VALUES (				3952,			'Gothic'		);
INSERT		INTO	Tag_Table			VALUES (				56690,			'On-Rails Shooter'		);
INSERT		INTO	Tag_Table			VALUES (				3955,			'Character Action Game'		);
INSERT		INTO	Tag_Table			VALUES (				11123,			'Mouse only'		);
INSERT		INTO	Tag_Table			VALUES (				3959,			'Rogue-lite'		);
INSERT		INTO	Tag_Table			VALUES (				9592,			'Dynamic Narration'		);
INSERT		INTO	Tag_Table			VALUES (				4474,			'CRPG'		);
INSERT		INTO	Tag_Table			VALUES (				16250,			'Gambling'		);
INSERT		INTO	Tag_Table			VALUES (				3964,			'Pixel Graphics'		);
INSERT		INTO	Tag_Table			VALUES (				5502,			'Hacking'		);
INSERT		INTO	Tag_Table			VALUES (				7038,			'Golf'		);
INSERT		INTO	Tag_Table			VALUES (				3968,			'Physics'		);
INSERT		INTO	Tag_Table			VALUES (				4486,			'Choose Your Own Adventure'		);
INSERT		INTO	Tag_Table			VALUES (				13190,			'America'		);
INSERT		INTO	Tag_Table			VALUES (				3978,			'Survival Horror'		);
INSERT		INTO	Tag_Table			VALUES (				8075,			'TrackIR'		);
INSERT		INTO	Tag_Table			VALUES (				7569,			'Grid-Based Movement'		);
INSERT		INTO	Tag_Table			VALUES (				3987,			'Historical'		);
INSERT		INTO	Tag_Table			VALUES (				6041,			'Horses'		);
INSERT		INTO	Tag_Table			VALUES (				17305,			'Strategy RPG'		);
INSERT		INTO	Tag_Table			VALUES (				4508,			'Co-op Campaign'		);
INSERT		INTO	Tag_Table			VALUES (				5537,			'Puzzle-Platformer'		);
INSERT		INTO	Tag_Table			VALUES (				4004,			'Retro'		);
INSERT		INTO	Tag_Table			VALUES (				6052,			'Noir'		);
INSERT		INTO	Tag_Table			VALUES (				1445,			'Software Training'		);
INSERT		INTO	Tag_Table			VALUES (				5030,			'Dystopian '		);
INSERT		INTO	Tag_Table			VALUES (				5547,			'Arena Shooter'		);
INSERT		INTO	Tag_Table			VALUES (				22955,			'Mini Golf'		);
INSERT		INTO	Tag_Table			VALUES (				4018,			'Vampire'		);
INSERT		INTO	Tag_Table			VALUES (				10679,			'Time Travel'		);
INSERT		INTO	Tag_Table			VALUES (				17337,			'Lemmings'		);
INSERT		INTO	Tag_Table			VALUES (				4026,			'Difficult'		);
INSERT		INTO	Tag_Table			VALUES (				8122,			'Level Editor'		);
INSERT		INTO	Tag_Table			VALUES (				5055,			'e-sports'		);
INSERT		INTO	Tag_Table			VALUES (				7107,			'Real-Time with Pause'		);
INSERT		INTO	Tag_Table			VALUES (				24003,			'Word Game'		);
INSERT		INTO	Tag_Table			VALUES (				4036,			'Parkour'		);
INSERT		INTO	Tag_Table			VALUES (				9157,			'Underwater'		);
INSERT		INTO	Tag_Table			VALUES (				123332,			'Bikes'		);
INSERT		INTO	Tag_Table			VALUES (				7622,			'Offroad'		);
INSERT		INTO	Tag_Table			VALUES (				10695,			'Party-Based RPG'		);
INSERT		INTO	Tag_Table			VALUES (				5577,			'RPGMaker'		);
INSERT		INTO	Tag_Table			VALUES (				7113,			'Crowdfunded'		);
INSERT		INTO	Tag_Table			VALUES (				4046,			'Dragons'		);
INSERT		INTO	Tag_Table			VALUES (				4559,			'Quick-Time Events'		);
INSERT		INTO	Tag_Table			VALUES (				4562,			'Cartoon'		);
INSERT		INTO	Tag_Table			VALUES (				13782,			'Experimental'		);
INSERT		INTO	Tag_Table			VALUES (				4057,			'Magic'		);
INSERT		INTO	Tag_Table			VALUES (				8666,			'Runner'		);
INSERT		INTO	Tag_Table			VALUES (				21978,			'VR'		);
INSERT		INTO	Tag_Table			VALUES (				13276,			'Tanks'		);
INSERT		INTO	Tag_Table			VALUES (				6621,			'Pinball'		);
INSERT		INTO	Tag_Table			VALUES (				4064,			'Thriller'		);
INSERT		INTO	Tag_Table			VALUES (				6625,			'Time Manipulation'		);
INSERT		INTO	Tag_Table			VALUES (				198631,			'Mystery Dungeon'		);
INSERT		INTO	Tag_Table			VALUES (				5094,			'Narration'		);
INSERT		INTO	Tag_Table			VALUES (				5611,			'Mature'		);
INSERT		INTO	Tag_Table			VALUES (				15339,			'Documentary'		);
INSERT		INTO	Tag_Table			VALUES (				492,			'Indie'		);
INSERT		INTO	Tag_Table			VALUES (				5613,			'Detective'		);
INSERT		INTO	Tag_Table			VALUES (				4085,			'Anime'		);
INSERT		INTO	Tag_Table			VALUES (				4598,			'Alternate History'		);
INSERT		INTO	Tag_Table			VALUES (				6650,			'Nudity'		);
INSERT		INTO	Tag_Table			VALUES (				776177,			'360 Video'		);
INSERT		INTO	Tag_Table			VALUES (				4604,			'Dark Fantasy'		);
INSERT		INTO	Tag_Table			VALUES (				25085,			'Touch-Friendly'		);
INSERT		INTO	Tag_Table			VALUES (				4094,			'Minimalist'		);
INSERT		INTO	Tag_Table			VALUES (				12286,			'Warhammer 40K'		);
SET DEFINE ON;
