SET DEFINE OFF;
INSERT INTO company_table values( 1, 'Valve');
INSERT INTO company_table values( 2, 'Tripwire Interactive');
INSERT INTO company_table values( 3, 'id Software');
INSERT INTO company_table values( 4, 'Infinity Ward');
INSERT INTO company_table values( 5, 'Aspyr (Mac)');
INSERT INTO company_table values( 6, 'Frontier');
INSERT INTO company_table values( 7, 'PopCap Games, Inc.');
INSERT INTO company_table values( 8, 'Elixir Studios');
INSERT INTO company_table values( 9, 'Facepunch Studios');
INSERT INTO company_table values( 10, 'Relic Entertainment');
INSERT INTO company_table values( 11, 'The Creative Assembly');
INSERT INTO company_table values( 12, 'Feral Interactive (Mac)');
INSERT INTO company_table values( 13, 'Feral Interactive (Linux)');
INSERT INTO company_table values( 14, 'GSC Game World');
INSERT INTO company_table values( 15, 'Pandemic Studios');
INSERT INTO company_table values( 16, 'Pyro Studios');
INSERT INTO company_table values( 17, 'Io-Interactive A/S');
INSERT INTO company_table values( 18, 'CCP');
INSERT INTO company_table values( 19, 'Firaxis Games');
INSERT INTO company_table values( 20, 'Irrational Games');
INSERT INTO company_table values( 21, 'Virtual Programming (Linux)');
INSERT INTO company_table values( 22, 'Aspyr (Mac, Linux)');
INSERT INTO company_table values( 23, 'Gray Matter Studios');
INSERT INTO company_table values( 24, 'Treyarch');
INSERT INTO company_table values( 25, 'Epic Games, Inc.');
INSERT INTO company_table values( 26, 'Feral Interactive (Mac/Linux)');
INSERT INTO company_table values( 27, 'Maxis¢â');
INSERT INTO company_table values( 28, 'EA Redwood Shores');
INSERT INTO company_table values( 29, 'TaleWorlds Entertainment');
INSERT INTO company_table values( 30, 'ACE Team');
INSERT INTO company_table values( 31, 'Bethesda Game Studios¢ç');
INSERT INTO company_table values( 32, 'Bethesda Game Studios');
INSERT INTO company_table values( 33, 'Obsidian Entertainment');
INSERT INTO company_table values( 34, 'Haemimont Games');
INSERT INTO company_table values( 35, 'EA - Maxis');
INSERT INTO company_table values( 36, 'EA Los Angeles');
INSERT INTO company_table values( 37, 'DICE');
INSERT INTO company_table values( 38, 'BioWare');
INSERT INTO company_table values( 39, 'Ubisoft Montreal');
INSERT INTO company_table values( 40, 'Rocksteady Studios');
INSERT INTO company_table values( 41, 'Amanita Design');
INSERT INTO company_table values( 42, 'Team Meat');
INSERT INTO company_table values( 43, 'FireFly Studios');
INSERT INTO company_table values( 44, 'Sledgehammer Games');
INSERT INTO company_table values( 45, 'Arrowhead Game Studios');
INSERT INTO company_table values( 46, 'Paradox Development Studio');
INSERT INTO company_table values( 47, 'Codemasters Racing');
INSERT INTO company_table values( 48, 'Visceral Games');
INSERT INTO company_table values( 49, 'Criterion Games');
INSERT INTO company_table values( 50, 'The Sims Studio');
INSERT INTO company_table values( 51, 'Cold Beam Games');
INSERT INTO company_table values( 52, 'Volition');
INSERT INTO company_table values( 53, 'Frictional Games');
INSERT INTO company_table values( 54, 'Terry Cavanagh');
INSERT INTO company_table values( 55, 'EasyGameStation');
INSERT INTO company_table values( 56, 'SEGA');
INSERT INTO company_table values( 57, 'Devil''s Details');
INSERT INTO company_table values( 58, 'Coffee Stain Studios');
INSERT INTO company_table values( 59, 'Zachtronics');
INSERT INTO company_table values( 60, 'Final Form Games');
INSERT INTO company_table values( 61, 'Messhof');
INSERT INTO company_table values( 62, 'Stainless Games');
INSERT INTO company_table values( 63, 'Gaslamp Games, Inc.');
INSERT INTO company_table values( 64, 'Ensemble Studios');
INSERT INTO company_table values( 65, 'Re-Logic');
INSERT INTO company_table values( 66, 'Supergiant Games');
INSERT INTO company_table values( 67, 'Zeboyd Games');
INSERT INTO company_table values( 68, 'The Indie Stone');
INSERT INTO company_table values( 69, 'Pocketwatch Games');
INSERT INTO company_table values( 70, 'Edmund McMillen and Florian Himsl');
INSERT INTO company_table values( 71, 'Runic Games');
INSERT INTO company_table values( 72, 'Nicalis, Inc.');
INSERT INTO company_table values( 73, 'Studio Pixel');
INSERT INTO company_table values( 74, 'The Behemoth');
INSERT INTO company_table values( 75, 'Techland');
INSERT INTO company_table values( 76, 'Arkane Studios');
INSERT INTO company_table values( 77, 'Suspicious Developments');
INSERT INTO company_table values( 78, 'Freebird Games');
INSERT INTO company_table values( 79, 'BlinkWorks Media');
INSERT INTO company_table values( 80, 'Nihon Falcom');
INSERT INTO company_table values( 81, 'Telltale Games');
INSERT INTO company_table values( 82, 'Muse Games');
INSERT INTO company_table values( 83, 'Love Conquers All Games');
INSERT INTO company_table values( 84, 'Chucklefish');
INSERT INTO company_table values( 85, 'Sumo Digital');
INSERT INTO company_table values( 86, 'Subset Games');
INSERT INTO company_table values( 87, 'Daybreak Game Company');
INSERT INTO company_table values( 88, 'Level Up Labs, LLC');
INSERT INTO company_table values( 89, 'Torn Banner Studios');
INSERT INTO company_table values( 90, 'Alexander Bruce');
INSERT INTO company_table values( 91, 'Crate Entertainment');
INSERT INTO company_table values( 92, 'Squad');
INSERT INTO company_table values( 93, 'Ubisoft Montreal, Massive Entertainment, and Ubisoft Shanghai');
INSERT INTO company_table values( 94, 'Ninja Theory');
INSERT INTO company_table values( 95, 'Galactic Cafe');
INSERT INTO company_table values( 96, 'Code Mystics');
INSERT INTO company_table values( 97, 'Eugen Systems');
INSERT INTO company_table values( 98, 'New World Interactive');
INSERT INTO company_table values( 99, 'SNK Playmore');
INSERT INTO company_table values( 100, 'Polytron Corporation');
INSERT INTO company_table values( 101, 'Starbreeze Studios AB');
INSERT INTO company_table values( 102, 'Wormwood Studios');
INSERT INTO company_table values( 103, 'Minority Media Inc.');
INSERT INTO company_table values( 104, 'Rebellion');
INSERT INTO company_table values( 105, 'SCS Software');
INSERT INTO company_table values( 106, 'Reto-Moto');
INSERT INTO company_table values( 107, 'Double Fine Productions');
INSERT INTO company_table values( 108, 'Shiny Shoe');
INSERT INTO company_table values( 109, 'Iron Galaxy Studios');
INSERT INTO company_table values( 110, 'Metanet Software Inc.');
INSERT INTO company_table values( 111, 'Giant Army');
INSERT INTO company_table values( 112, 'Olli Harjola, Otto Hantula, Tom Jubert, Carlo Castellano');
INSERT INTO company_table values( 113, 'Wolfire Games');
INSERT INTO company_table values( 114, 'CyberConnect2 Co. Ltd.');
INSERT INTO company_table values( 115, 'Ubisoft Toronto');
INSERT INTO company_table values( 116, 'Humble Hearts LLC');
INSERT INTO company_table values( 117, 'Gaijin Entertainment');
INSERT INTO company_table values( 118, 'Mine Loader Software Co., Ltd.');
INSERT INTO company_table values( 119, 'Red Barrels');
INSERT INTO company_table values( 120, '3909');
INSERT INTO company_table values( 121, 'Vlambeer');
INSERT INTO company_table values( 122, 'Carlsen Games');
INSERT INTO company_table values( 123, 'Shining Rock Software LLC');
INSERT INTO company_table values( 124, 'Gearbox Software');
INSERT INTO company_table values( 125, 'Kunos Simulazioni');
INSERT INTO company_table values( 126, 'Lab Zero Games');
INSERT INTO company_table values( 127, 'Ironhide Game Studio');
INSERT INTO company_table values( 128, 'Ndemic Creations');
INSERT INTO company_table values( 129, 'Vertigo Gaming Inc.');
INSERT INTO company_table values( 130, 'Brace Yourself Games');
INSERT INTO company_table values( 131, 'Studio Bean');
INSERT INTO company_table values( 132, 'GalaxyTrail');
INSERT INTO company_table values( 133, 'KillHouse Games');
INSERT INTO company_table values( 134, 'Hopoo Games, LLC');
INSERT INTO company_table values( 135, 'Priority Interrupt');
INSERT INTO company_table values( 136, 'Witch Beam');
INSERT INTO company_table values( 137, 'DotEmu');
INSERT INTO company_table values( 138, 'sparsevector');
INSERT INTO company_table values( 139, 'Yacht Club Games');
INSERT INTO company_table values( 140, 'Hanako Games');
INSERT INTO company_table values( 141, 'Image & Form');
INSERT INTO company_table values( 142, 'Rocketcat Games');
INSERT INTO company_table values( 143, 'Psyonix, Inc.');
INSERT INTO company_table values( 144, 'Gears for Breakfast');
INSERT INTO company_table values( 145, 'Treasure');
INSERT INTO company_table values( 146, 'Colossal Order Ltd.');
INSERT INTO company_table values( 147, 'Ubisoft Montr?al');
INSERT INTO company_table values( 148, 'Croteam');
INSERT INTO company_table values( 149, 'Netcore Games');
INSERT INTO company_table values( 150, 'Ubisoft Montpellier');
INSERT INTO company_table values( 151, 'JoWooD Vienna');
INSERT INTO company_table values( 152, 'Team Reptile');
INSERT INTO company_table values( 153, 'Moon Studios GmbH');
INSERT INTO company_table values( 154, 'Xtal Sword');
INSERT INTO company_table values( 155, 'Red Hook Studios');
INSERT INTO company_table values( 156, 'Oovee¢ç Game Studios');
INSERT INTO company_table values( 157, 'Arc System Works');
INSERT INTO company_table values( 158, 'Silver Dollar Games');
INSERT INTO company_table values( 159, 'Unknown Worlds Entertainment');
INSERT INTO company_table values( 160, 'Matt Roszak');
INSERT INTO company_table values( 161, 'Matthew Brown');
INSERT INTO company_table values( 162, 'Thomas Bowker');
INSERT INTO company_table values( 163, 'Defiant Development');
INSERT INTO company_table values( 164, 'StudioMDHR Entertainment Inc.');
INSERT INTO company_table values( 165, 'Elias Viglione');
INSERT INTO company_table values( 166, 'Jussi Kukkonen');
INSERT INTO company_table values( 167, 'Pixel Ferrets');
INSERT INTO company_table values( 168, 'Laminar Research');
INSERT INTO company_table values( 169, 'SFB Games');
INSERT INTO company_table values( 170, 'State of Play Games');
INSERT INTO company_table values( 171, 'Free Lives');
INSERT INTO company_table values( 172, 'Stellar Jockeys');
INSERT INTO company_table values( 173, 'Gausswerks');
INSERT INTO company_table values( 174, 'DrinkBox Studios');
INSERT INTO company_table values( 175, 'Vanguard Games');
INSERT INTO company_table values( 176, '343 Industries');
INSERT INTO company_table values( 177, 'KOEI TECMO GAMES CO., LTD.');
INSERT INTO company_table values( 178, 'Alastair John Jack');
INSERT INTO company_table values( 179, 'Knuckle Cracker');
INSERT INTO company_table values( 180, 'Dreamworlds');
INSERT INTO company_table values( 181, '11 bit studios');
INSERT INTO company_table values( 182, 'The Game Kitchen');
INSERT INTO company_table values( 183, 'Chris Sawyer Productions');
INSERT INTO company_table values( 184, 'YOTSUBANE');
INSERT INTO company_table values( 185, 'Adventure Planning Service');
INSERT INTO company_table values( 186, 'Berserk Games');
INSERT INTO company_table values( 187, 'ALICE IN DISSONANCE');
INSERT INTO company_table values( 188, '4A Games');
INSERT INTO company_table values( 189, 'DigiFX Interactive');
INSERT INTO company_table values( 190, 'Konami Digital Entertainment');
INSERT INTO company_table values( 191, 'Dinosaur Polo Club');
INSERT INTO company_table values( 192, 'Fireproof Games');
INSERT INTO company_table values( 193, 'Lionhead Studios');
INSERT INTO company_table values( 194, 'Firaxis');
INSERT INTO company_table values( 195, 'League of Geeks');
INSERT INTO company_table values( 196, 'Counterplay Games Inc.');
INSERT INTO company_table values( 197, 'Powerhoof');
INSERT INTO company_table values( 198, 'Ludeon Studios');
INSERT INTO company_table values( 199, 'Andy Wallace');
INSERT INTO company_table values( 200, 'Game in a Bottle');
INSERT INTO company_table values( 201, 'Team Junkfish');
INSERT INTO company_table values( 202, 'Cavedog Entertainment');
INSERT INTO company_table values( 203, 'Ubisoft Montreal, Red Storm, Shanghai, Toronto, Kiev');
INSERT INTO company_table values( 204, 'Ole Lange');
INSERT INTO company_table values( 205, 'Crytek');
INSERT INTO company_table values( 206, 'Fabio Ferrara');
INSERT INTO company_table values( 207, 'Trion Worlds');
INSERT INTO company_table values( 208, 'Ubisoft Quebec');
INSERT INTO company_table values( 209, 'Blue Byte');
INSERT INTO company_table values( 210, 'Failbetter Games');
INSERT INTO company_table values( 211, 'Smartly Dressed Games');
INSERT INTO company_table values( 212, 'Hinterland Studio Inc.');
INSERT INTO company_table values( 213, 'Ninja Kiwi');
INSERT INTO company_table values( 214, 'Deli Interactive LLC');
INSERT INTO company_table values( 215, 'CreativeForge Games');
INSERT INTO company_table values( 216, 'Mediatonic');
INSERT INTO company_table values( 217, 'Hato Moa');
INSERT INTO company_table values( 218, 'The Irregular Corporation');
INSERT INTO company_table values( 219, '07th Expansion');
INSERT INTO company_table values( 220, 'Capcom');
INSERT INTO company_table values( 221, 'Ubisoft Sofia');
INSERT INTO company_table values( 222, 'Ubisoft Kiev');
INSERT INTO company_table values( 223, 'Dodge Roll');
INSERT INTO company_table values( 224, 'Landon Podbielski');
INSERT INTO company_table values( 225, 'Beam Team Games');
INSERT INTO company_table values( 226, 'Microsoft Game Studios');
INSERT INTO company_table values( 227, 'Sharpened Edge Studios');
INSERT INTO company_table values( 228, 'minori');
INSERT INTO company_table values( 229, 'VisualArts/Key');
INSERT INTO company_table values( 230, 'Cross-Product');
INSERT INTO company_table values( 231, 'Heartbit Interactive');
INSERT INTO company_table values( 232, 'Scott Cawthon');
INSERT INTO company_table values( 233, 'DONTNOD Entertainment');
INSERT INTO company_table values( 234, 'Batterystaple Games');
INSERT INTO company_table values( 235, 'Fire Hose Games');
INSERT INTO company_table values( 236, 'RobTop Games');
INSERT INTO company_table values( 237, 'Klei Entertainment');
INSERT INTO company_table values( 238, 'Indimo Labs LLC');
INSERT INTO company_table values( 239, 'THQ Nordic');
INSERT INTO company_table values( 240, 'Slick Entertainment Inc.');
INSERT INTO company_table values( 241, 'CAPCOM Co., Ltd.');
INSERT INTO company_table values( 242, 'Infinity Plus 2');
INSERT INTO company_table values( 243, 'Anisoptera Games');
INSERT INTO company_table values( 244, 'HandMade Game');
INSERT INTO company_table values( 245, 'Soviet Games');
INSERT INTO company_table values( 246, 'Forgotten Key');
INSERT INTO company_table values( 247, 'Thomas Happ Games LLC');
INSERT INTO company_table values( 248, 'Freehold Games');
INSERT INTO company_table values( 249, 'Splash Damage');
INSERT INTO company_table values( 250, 'BlankMediaGames');
INSERT INTO company_table values( 251, 'Trese Brothers');
INSERT INTO company_table values( 252, 'Dingaling');
INSERT INTO company_table values( 253, 'Sujin Ri');
INSERT INTO company_table values( 254, 'Yunjeong Yun');
INSERT INTO company_table values( 255, 'Hyein Go');
INSERT INTO company_table values( 256, 'Minsu Ock');
INSERT INTO company_table values( 257, 'Marcos Arroyo');
INSERT INTO company_table values( 258, 'Seona Lee');
INSERT INTO company_table values( 259, 'Sohyeon Jeon');
INSERT INTO company_table values( 260, 'Choice of Games');
INSERT INTO company_table values( 261, 'KIXEYE');
INSERT INTO company_table values( 262, 'Pixellore');
INSERT INTO company_table values( 263, 'Sun-Studios');
INSERT INTO company_table values( 264, 'Eggcode');
INSERT INTO company_table values( 265, 'Leslaw Sliwko');
INSERT INTO company_table values( 266, 'Steel Crate Games');
INSERT INTO company_table values( 267, 'David Stark');
INSERT INTO company_table values( 268, 'Shorebound Studios');
INSERT INTO company_table values( 269, 'Cat5Games');
INSERT INTO company_table values( 270, 'Spiderling Studios');
INSERT INTO company_table values( 271, 'Studio Wildcard');
INSERT INTO company_table values( 272, 'Instinct Games');
INSERT INTO company_table values( 273, 'Efecto Studios');
INSERT INTO company_table values( 274, 'Virtual Basement LLC');
INSERT INTO company_table values( 275, 'Niffler Ltd.');
INSERT INTO company_table values( 276, 'ÍÔÍÅ??êÍ??');
INSERT INTO company_table values( 277, 'Ð¹í­Úì');
INSERT INTO company_table values( 278, 'Littlewitch');
INSERT INTO company_table values( 279, 'MachineGames');
INSERT INTO company_table values( 280, 'Ellada Games');
INSERT INTO company_table values( 281, 'Abnormal Software');
INSERT INTO company_table values( 282, 'Holy Priest');
INSERT INTO company_table values( 283, 'Four Quarters');
INSERT INTO company_table values( 284, 'Zandel Media');
INSERT INTO company_table values( 285, 'Rumpus');
INSERT INTO company_table values( 286, 'Totally Games');
INSERT INTO company_table values( 287, 'Evan Tognotti');
INSERT INTO company_table values( 288, 'Lukas Jaeckel');
INSERT INTO company_table values( 289, 'Twelve Tiles');
INSERT INTO company_table values( 290, 'Valsar');
INSERT INTO company_table values( 291, 'Brainchild');
INSERT INTO company_table values( 292, 'Chris Sawyer');
INSERT INTO company_table values( 293, 'Walter Machado');
INSERT INTO company_table values( 294, 'Eric Hornby');
INSERT INTO company_table values( 295, 'David Szymanski');
INSERT INTO company_table values( 296, 'Interplay Entertainment Corp.');
INSERT INTO company_table values( 297, 'Moppin');
INSERT INTO company_table values( 298, 'System Era Softworks');
INSERT INTO company_table values( 299, 'oddonegames');
INSERT INTO company_table values( 300, 'Ed Curtis-Sivess');
INSERT INTO company_table values( 301, 'Bare Mettle Entertainment');
INSERT INTO company_table values( 302, 'Coredumping');
INSERT INTO company_table values( 303, 'Killmonday Games AB');
INSERT INTO company_table values( 304, 'Crowbar Collective');
INSERT INTO company_table values( 305, 'NeoNight');
INSERT INTO company_table values( 306, 'Clever-Plays');
INSERT INTO company_table values( 307, 'Playsaurus');
INSERT INTO company_table values( 308, 'Shiver Games');
INSERT INTO company_table values( 309, 'John Wizard');
INSERT INTO company_table values( 310, 'Creative Assembly');
INSERT INTO company_table values( 311, 'Legend Studio');
INSERT INTO company_table values( 312, 'Zoo Corporation');
INSERT INTO company_table values( 313, 'Panic Ensues Software');
INSERT INTO company_table values( 314, 'Chu-3');
INSERT INTO company_table values( 315, 'Bakufu Narayama');
INSERT INTO company_table values( 316, 'Team Fractal Alligator');
INSERT INTO company_table values( 317, 'Massive Entertainment');
INSERT INTO company_table values( 318, 'Vasily Voronkov');
INSERT INTO company_table values( 319, 'Ryan Joseph');
INSERT INTO company_table values( 320, 'Peter Kosyh');
INSERT INTO company_table values( 321, 'Pixel Prophecy');
INSERT INTO company_table values( 322, 'Dry Cactus');
INSERT INTO company_table values( 323, 'Team Cherry');
INSERT INTO company_table values( 324, 'Maciej Targoni');
INSERT INTO company_table values( 325, 'Wojciech Wasiak');
INSERT INTO company_table values( 326, 'Radical Fish Games');
INSERT INTO company_table values( 327, 'Robot Gentleman');
INSERT INTO company_table values( 328, 'Sam Barlow');
INSERT INTO company_table values( 329, 'Ubisoft Quebec, in collaboration with Ubisoft Annecy, Bucharest, Kiev, Montreal, Montpellier, Shanghai, Singapore, Sofia, Toronto studios');
INSERT INTO company_table values( 330, 'Andrettin');
INSERT INTO company_table values( 331, 'John Cullen');
INSERT INTO company_table values( 332, 'Visual Concepts');
INSERT INTO company_table values( 333, 'Clifftop Games');
INSERT INTO company_table values( 334, 'Corrosive Studios LLC');
INSERT INTO company_table values( 335, 'Muzzy Lane Software');
INSERT INTO company_table values( 336, 'Deion Mobile');
INSERT INTO company_table values( 337, 'Russpuppy');
INSERT INTO company_table values( 338, 'Blake Garner');
INSERT INTO company_table values( 339, 'FIVE-BN GAMES');
INSERT INTO company_table values( 340, 'Larian Studios');
INSERT INTO company_table values( 341, 'Capribyte Studios');
INSERT INTO company_table values( 342, '¡â¡Û¡à¡¿ (Miwashiba)');
INSERT INTO company_table values( 343, 'Keen Games');
INSERT INTO company_table values( 344, 'FromSoftware, Inc.');
INSERT INTO company_table values( 345, 'Kittehface Software');
INSERT INTO company_table values( 346, 'Zbigniew Ochman');
INSERT INTO company_table values( 347, 'Subworld');
INSERT INTO company_table values( 348, 'Creoteam');
INSERT INTO company_table values( 349, 'Anarchy Enterprises');
INSERT INTO company_table values( 350, 'Fervent');
INSERT INTO company_table values( 351, 'Kieffer Bros.');
INSERT INTO company_table values( 352, 'Smarter Games');
INSERT INTO company_table values( 353, 'CAVE Interactive CO.,LTD.');
INSERT INTO company_table values( 354, 'i273 LLC');
INSERT INTO company_table values( 355, 'Gnarled Scar Manipulations');
INSERT INTO company_table values( 356, 'Sebastian Krzyszkowiak');
INSERT INTO company_table values( 357, 'Konrad Burandt');
INSERT INTO company_table values( 358, 'Pawe©© Radej');
INSERT INTO company_table values( 359, 'Eleon Game Studios');
INSERT INTO company_table values( 360, 'studiocime');
INSERT INTO company_table values( 361, 'Denneko Yuugi');
INSERT INTO company_table values( 362, 'Giant Squid');
INSERT INTO company_table values( 363, 'Sketchy Logic');
INSERT INTO company_table values( 364, 'Triverske');
INSERT INTO company_table values( 365, 'Jurlo');
INSERT INTO company_table values( 366, 'JetPackGone');
INSERT INTO company_table values( 367, 'EyeSpyda Games');
INSERT INTO company_table values( 368, 'Puzzle Lab');
INSERT INTO company_table values( 369, 'Hi-Rez Studios');
INSERT INTO company_table values( 370, 'Clever Endeavour Games');
INSERT INTO company_table values( 371, 'Liz-Arts');
INSERT INTO company_table values( 372, 'Axolot Games');
INSERT INTO company_table values( 373, 'Night School Studio');
INSERT INTO company_table values( 374, 'BANDAI NAMCO Studios Inc.');
INSERT INTO company_table values( 375, 'Daniel Mercier');
INSERT INTO company_table values( 376, 'Crystal Dynamics');
INSERT INTO company_table values( 377, 'tobyfox');
INSERT INTO company_table values( 378, 'Ezzat Studios');
INSERT INTO company_table values( 379, 'Bloober Team SA');
INSERT INTO company_table values( 380, 'AMPLITUDE Studios');
INSERT INTO company_table values( 381, 'Iceflake Studios');
INSERT INTO company_table values( 382, 'PixelTail Games');
INSERT INTO company_table values( 383, 'PixelFade Inc');
INSERT INTO company_table values( 384, 'ROCKFISH Games');
INSERT INTO company_table values( 385, 'Abrakam SA');
INSERT INTO company_table values( 386, 'Looterkings');
INSERT INTO company_table values( 387, 'Jundroo, LLC');
INSERT INTO company_table values( 388, 'Trav Nash');
INSERT INTO company_table values( 389, 'Wish Fang');
INSERT INTO company_table values( 390, 'CreSpirit');
INSERT INTO company_table values( 391, 'GemaYue');
INSERT INTO company_table values( 392, 'Running With Scissors');
INSERT INTO company_table values( 393, 'All Seeing Eye Games');
INSERT INTO company_table values( 394, 'Traveller''s Tales');
INSERT INTO company_table values( 395, 'TT Games');
INSERT INTO company_table values( 396, 'Dominique Grieshofer');
INSERT INTO company_table values( 397, 'Timushev Vladimir');
INSERT INTO company_table values( 398, 'Composer-Motorin Dmitry (Djinotan)');
INSERT INTO company_table values( 399, 'Jetdogs Studios');
INSERT INTO company_table values( 400, 'CorePunch Gamestudio');
INSERT INTO company_table values( 401, 'Sebastian Nigro');
INSERT INTO company_table values( 402, 'Panos Tzimas');
INSERT INTO company_table values( 403, 'FRENCH-BREAD');
INSERT INTO company_table values( 404, 'Tamsoft');
INSERT INTO company_table values( 405, 'Dylan Fitterer');
INSERT INTO company_table values( 406, 'MAGES. Inc.');
INSERT INTO company_table values( 407, 'ConcernedApe');
INSERT INTO company_table values( 408, 'Spike Chunsoft Co., Ltd.');
INSERT INTO company_table values( 409, 'Abstraction Games');
INSERT INTO company_table values( 410, 'Cuveet Story');
INSERT INTO company_table values( 411, 'Rad Codex');
INSERT INTO company_table values( 412, 'Happy Polygon');
INSERT INTO company_table values( 413, 'Lached Up Games');
INSERT INTO company_table values( 414, 'John Szymanski');
INSERT INTO company_table values( 415, 'Shawn Hitchcock');
INSERT INTO company_table values( 416, 'Vile Monarch');
INSERT INTO company_table values( 417, 'Tall Tail Studios');
INSERT INTO company_table values( 418, 'Yunus Ayyildiz');
INSERT INTO company_table values( 419, 'Sho Ohhira');
INSERT INTO company_table values( 420, 'Rooster Teeth Games');
INSERT INTO company_table values( 421, 'I-Illusions');
INSERT INTO company_table values( 422, 'Studio 4D');
INSERT INTO company_table values( 423, 'Little Cat Feet');
INSERT INTO company_table values( 424, 'Pilgrim Adventures');
INSERT INTO company_table values( 425, 'GrabTheGames Studios');
INSERT INTO company_table values( 426, 'Isaac Cohen');
INSERT INTO company_table values( 427, 'VaragtP');
INSERT INTO company_table values( 428, 'Hosted Games');
INSERT INTO company_table values( 429, 'Sorath');
INSERT INTO company_table values( 430, '3Division');
INSERT INTO company_table values( 431, 'SnoutUp');
INSERT INTO company_table values( 432, 'Tarsier Studios');
INSERT INTO company_table values( 433, 'Wube Software LTD.');
INSERT INTO company_table values( 434, 'Square Enix Montr?al');
INSERT INTO company_table values( 435, 'Bombservice');
INSERT INTO company_table values( 436, 'Redshift');
INSERT INTO company_table values( 437, 'GOGII Games');
INSERT INTO company_table values( 438, 'Triangular Pixels');
INSERT INTO company_table values( 439, 'Modern Visual Arts Laboratory');
INSERT INTO company_table values( 440, 'SEO INSEOK');
INSERT INTO company_table values( 441, 'Blacklight Interactive');
INSERT INTO company_table values( 442, '2Chance Projects');
INSERT INTO company_table values( 443, 'IIchan Eroge Team');
INSERT INTO company_table values( 444, 'Wayward Prophet');
INSERT INTO company_table values( 445, 'Monomi Park');
INSERT INTO company_table values( 446, 'Nickervision Studios');
INSERT INTO company_table values( 447, 'Big Corporation');
INSERT INTO company_table values( 448, 'Hunter Studio');
INSERT INTO company_table values( 449, 'Room710Games');
INSERT INTO company_table values( 450, 'Rusty Lake');
INSERT INTO company_table values( 451, 'REL Games');
INSERT INTO company_table values( 452, 'Date Nighto');
INSERT INTO company_table values( 453, 'Adriaan de Jongh');
INSERT INTO company_table values( 454, 'Sylvain Tegroeg');
INSERT INTO company_table values( 455, 'Futuretown');
INSERT INTO company_table values( 456, 'Survios');
INSERT INTO company_table values( 457, 'Innerspace VR');
INSERT INTO company_table values( 458, 'BlackSpot Entertainment');
INSERT INTO company_table values( 459, 'Aldin Dynamics');
INSERT INTO company_table values( 460, 'Pixel Trickery');
INSERT INTO company_table values( 461, 'Sunward Games');
INSERT INTO company_table values( 462, 'Art in Heart');
INSERT INTO company_table values( 463, 'Goblinz');
INSERT INTO company_table values( 464, 'Burak Dabak');
INSERT INTO company_table values( 465, 'Freedomize Studio');
INSERT INTO company_table values( 466, 'Baroque Decay');
INSERT INTO company_table values( 467, 'Wargaming Group Limited');
INSERT INTO company_table values( 468, 'Giants Software');
INSERT INTO company_table values( 469, 'Ubisoft');
INSERT INTO company_table values( 470, 'Sukeban Games');
INSERT INTO company_table values( 471, 'Frontier Developments');
INSERT INTO company_table values( 472, 'Nawia Games');
INSERT INTO company_table values( 473, 'Ghost Town Games Ltd.');
INSERT INTO company_table values( 474, 'Alice & Smith');
INSERT INTO company_table values( 475, 'Thing Trunk');
INSERT INTO company_table values( 476, 'Revival Productions, LLC');
INSERT INTO company_table values( 477, 'RUST LTD.');
INSERT INTO company_table values( 478, 'Airship Syndicate');
INSERT INTO company_table values( 479, 'Wevr, Inc.');
INSERT INTO company_table values( 480, 'Trinket Studios');
INSERT INTO company_table values( 481, 'Cygames, Inc.');
INSERT INTO company_table values( 482, 'Arif Games');
INSERT INTO company_table values( 483, 'Moltenplay');
INSERT INTO company_table values( 484, '[OneManBand]');
INSERT INTO company_table values( 485, 'QLOC');
INSERT INTO company_table values( 486, 'DIMPS');
INSERT INTO company_table values( 487, 'xXarabongXx');
INSERT INTO company_table values( 488, 'Rebelephant');
INSERT INTO company_table values( 489, 'TreeFortress Games');
INSERT INTO company_table values( 490, 'Michaela Laws');
INSERT INTO company_table values( 491, 'Organic 2 Digital Studio');
INSERT INTO company_table values( 492, 'Watercress Studios');
INSERT INTO company_table values( 493, 'Ubisoft Paris');
INSERT INTO company_table values( 494, 'Ubisoft Annecy');
INSERT INTO company_table values( 495, 'Ubisoft Bucharest');
INSERT INTO company_table values( 496, 'Ubisoft Milan');
INSERT INTO company_table values( 497, 'Reflections');
INSERT INTO company_table values( 498, 'Chandler Rounsley');
INSERT INTO company_table values( 499, 'Michal Pawlowski');
INSERT INTO company_table values( 500, 'Lapovich');
INSERT INTO company_table values( 501, 'YETU GAME');
INSERT INTO company_table values( 502, 'Out of the Park Developments');
INSERT INTO company_table values( 503, '?â©ÍïíÂãø');
INSERT INTO company_table values( 504, 'Vladimir Maslov');
INSERT INTO company_table values( 505, 'Kyrylo Kuzyk');
INSERT INTO company_table values( 506, 'TPP Studio');
INSERT INTO company_table values( 507, 'Big Cow Studios');
INSERT INTO company_table values( 508, 'takk');
INSERT INTO company_table values( 509, 'Against Gravity¢ç');
INSERT INTO company_table values( 510, 'Jon Sudbury Games');
INSERT INTO company_table values( 511, 'DreaMory');
INSERT INTO company_table values( 512, 'Manuel Pazos');
INSERT INTO company_table values( 513, 'Daniel Celem?n');
INSERT INTO company_table values( 514, 'Nerial');
INSERT INTO company_table values( 515, 'Pixel vs Pixel');
INSERT INTO company_table values( 516, 'Arzola''s');
INSERT INTO company_table values( 517, 'CloudGate Studio, Inc.');
INSERT INTO company_table values( 518, 'Nippon Ichi Software, Inc.');
INSERT INTO company_table values( 519, 'ClickGames');
INSERT INTO company_table values( 520, 'Sports Interactive');
INSERT INTO company_table values( 521, 'Zach Tsiakalis-Brown');
INSERT INTO company_table values( 522, 'Bad Bird Studios');
INSERT INTO company_table values( 523, 'ZOV GAME STUDIO');
INSERT INTO company_table values( 524, 'Green127');
INSERT INTO company_table values( 525, 'Might and Delight');
INSERT INTO company_table values( 526, 'Halfbrick Studios Pty Ltd');
INSERT INTO company_table values( 527, 'For Fun Labs');
INSERT INTO company_table values( 528, 'Vifth Floor');
INSERT INTO company_table values( 529, 'Billy Goat Entertainment Ltd');
INSERT INTO company_table values( 530, 'üé?ô¸?');
INSERT INTO company_table values( 531, 'The Secret Location');
INSERT INTO company_table values( 532, 'CottonGame');
INSERT INTO company_table values( 533, 'lingtanstudio');
INSERT INTO company_table values( 534, 'Cats Who Play');
INSERT INTO company_table values( 535, 'Reddoll Srl');
INSERT INTO company_table values( 536, 'Red Matter Studio');
INSERT INTO company_table values( 537, 'Realmforge Studios');
INSERT INTO company_table values( 538, 'Blue Giraffe');
INSERT INTO company_table values( 539, 'hOSHI');
INSERT INTO company_table values( 540, 'Phaser Lock Interactive');
INSERT INTO company_table values( 541, 'Michal Kruba');
INSERT INTO company_table values( 542, 'JCKSLAP');
INSERT INTO company_table values( 543, 'Pavel Jamal');
INSERT INTO company_table values( 544, 'Noio');
INSERT INTO company_table values( 545, 'Somi');
INSERT INTO company_table values( 546, 'BigCheeseGames');
INSERT INTO company_table values( 547, 'Rabbiton');
INSERT INTO company_table values( 548, 'HA Studio Ltd.');
INSERT INTO company_table values( 549, 'Giant Sparrow');
INSERT INTO company_table values( 550, 'Midnight Party');
INSERT INTO company_table values( 551, 'Aleksandr Golovkin');
INSERT INTO company_table values( 552, 'Sierra');
INSERT INTO company_table values( 553, 'Cartboard Games');
INSERT INTO company_table values( 554, 'COLOPL, Inc.');
INSERT INTO company_table values( 555, 'Jutsu Games');
INSERT INTO company_table values( 556, 'Stress Level Zero');
INSERT INTO company_table values( 557, 'OperaHouse Corporation');
INSERT INTO company_table values( 558, 'Ludomotion');
INSERT INTO company_table values( 559, 'Blastoid Entertainment');
INSERT INTO company_table values( 560, 'RLTY CHK');
INSERT INTO company_table values( 561, 'Marvelous Inc.');
INSERT INTO company_table values( 562, 'ùë?ÐôÎ¡Ðü');
INSERT INTO company_table values( 563, 'Home Net Games');
INSERT INTO company_table values( 564, 'Matt Dabrowski');
INSERT INTO company_table values( 565, 'Enigmatic');
INSERT INTO company_table values( 566, 'Toast');
INSERT INTO company_table values( 567, 'From The Bard');
INSERT INTO company_table values( 568, 'Wizard Games Inc');
INSERT INTO company_table values( 569, 'ProGames Studio');
INSERT INTO company_table values( 570, 'FIREBEAST');
INSERT INTO company_table values( 571, 'Brian Lindenhof');
INSERT INTO company_table values( 572, 'batensan');
INSERT INTO company_table values( 573, 'DIVR Labs');
INSERT INTO company_table values( 574, 'CFK Co., Ltd.');
INSERT INTO company_table values( 575, 'Kyle Seeley');
INSERT INTO company_table values( 576, 'HypeTrain Digital');
INSERT INTO company_table values( 577, 'Spicy Tails');
INSERT INTO company_table values( 578, 'The Munky');
INSERT INTO company_table values( 579, 'Taylor Stapleton');
INSERT INTO company_table values( 580, 'Three Fields Entertainment');
INSERT INTO company_table values( 581, 'Quiet River');
INSERT INTO company_table values( 582, 'Sirius Sam');
INSERT INTO company_table values( 583, 'Runner Duck');
INSERT INTO company_table values( 584, 'Owlet');
INSERT INTO company_table values( 585, 'nDreams / Near Light');
INSERT INTO company_table values( 586, 'Pillow Fight');
INSERT INTO company_table values( 587, 'TheMiddleGray');
INSERT INTO company_table values( 588, 'GameHouse');
INSERT INTO company_table values( 589, 'DaGGaSoft');
INSERT INTO company_table values( 590, 'Entwell Co., Ltd.');
INSERT INTO company_table values( 591, 'NS STUDIO');
INSERT INTO company_table values( 592, 'Tricol Co., Ltd.');
INSERT INTO company_table values( 593, 'Sourcenity GmbH');
INSERT INTO company_table values( 594, 'Square Enix');
INSERT INTO company_table values( 595, 'FantaBlade Network');
INSERT INTO company_table values( 596, '10Ants Hill');
INSERT INTO company_table values( 597, 'Chris Chung');
INSERT INTO company_table values( 598, 'Fifth One');
INSERT INTO company_table values( 599, 'Game Science');
INSERT INTO company_table values( 600, 'Barrel Roll Games');
INSERT INTO company_table values( 601, 'Construct Studio');
INSERT INTO company_table values( 602, 'Kitsune Games');
INSERT INTO company_table values( 603, 'Battlecruiser Games');
INSERT INTO company_table values( 604, 'Impressions Games');
INSERT INTO company_table values( 605, 'Falcoware');
INSERT INTO company_table values( 606, 'btf GmbH');
INSERT INTO company_table values( 607, 'Circus Atos');
INSERT INTO company_table values( 608, 'Zoom Out Games');
INSERT INTO company_table values( 609, 'Project Moon');
INSERT INTO company_table values( 610, 'Lion Shield, LLC');
INSERT INTO company_table values( 611, 'Tyler Hurd');
INSERT INTO company_table values( 612, 'SNK CORPORATION');
INSERT INTO company_table values( 613, 'MyDearest');
INSERT INTO company_table values( 614, 'storyk21674');
INSERT INTO company_table values( 615, 'STILILA');
INSERT INTO company_table values( 616, '?Ó±');
INSERT INTO company_table values( 617, 'LaboRatStudio');
INSERT INTO company_table values( 618, 'Funghisoft');
INSERT INTO company_table values( 619, 'rebel rabbit');
INSERT INTO company_table values( 620, 'Ovid Works');
INSERT INTO company_table values( 621, 'Prideful Sloth');
INSERT INTO company_table values( 622, 'Every Single Soldier');
INSERT INTO company_table values( 623, 'Retro Epic');
INSERT INTO company_table values( 624, 'StevenHarmonGames');
INSERT INTO company_table values( 625, 'Broken Rules');
INSERT INTO company_table values( 626, 'Ran');
INSERT INTO company_table values( 627, '22cans');
INSERT INTO company_table values( 628, 'Christian Whitehead');
INSERT INTO company_table values( 629, 'Headcannon');
INSERT INTO company_table values( 630, 'PagodaWest Games');
INSERT INTO company_table values( 631, 'Abigail Corfman');
INSERT INTO company_table values( 632, 'BekkerDev Studio');
INSERT INTO company_table values( 633, 'Motion Twin');
INSERT INTO company_table values( 634, 'Dr_Crewcut');
INSERT INTO company_table values( 635, 'White Door Games');
INSERT INTO company_table values( 636, 'Anvil Game Studios');
INSERT INTO company_table values( 637, 'Konami Digital Entertainment Co., Ltd.');
INSERT INTO company_table values( 638, 'The Gentlebros');
INSERT INTO company_table values( 639, 'Imperium42¢ç Game Studio');
INSERT INTO company_table values( 640, 'Dylan "Xblade" Hunt');
INSERT INTO company_table values( 641, 'Elsa "FieryElsa" Hunt');
INSERT INTO company_table values( 642, 'Boslof');
INSERT INTO company_table values( 643, 'Arnoldas "Arnenzo" Jegorovas');
INSERT INTO company_table values( 644, 'Adityaraj "Adiart" Jain');
INSERT INTO company_table values( 645, 'Mel "Xed" Kim');
INSERT INTO company_table values( 646, 'Stephen "Teahacker" Wise');
INSERT INTO company_table values( 647, 'Dan "ISWThunder" Holzhauer');
INSERT INTO company_table values( 648, 'Doborog Games');
INSERT INTO company_table values( 649, 'Kremlingames');
INSERT INTO company_table values( 650, '10kbit Games');
INSERT INTO company_table values( 651, 'Elven Workshop');
INSERT INTO company_table values( 652, 'Eternal Night Studios');
INSERT INTO company_table values( 653, 'Cat Nigiri');
INSERT INTO company_table values( 654, 'AQURIA');
INSERT INTO company_table values( 655, 'Nordic Trolls');
INSERT INTO company_table values( 656, 'Baba Yaga Games');
INSERT INTO company_table values( 657, 'Tree Men Games');
INSERT INTO company_table values( 658, 'Surreal Games');
INSERT INTO company_table values( 659, 'Paleno Games');
INSERT INTO company_table values( 660, 'Jake Hollands');
INSERT INTO company_table values( 661, 'Salvation');
INSERT INTO company_table values( 662, 'Emanon Studios');
INSERT INTO company_table values( 663, 'What Pumpkin Games, Inc.');
INSERT INTO company_table values( 664, 'Play:D');
INSERT INTO company_table values( 665, 'Blender Games');
INSERT INTO company_table values( 666, 'DIGIDICED');
INSERT INTO company_table values( 667, 'KOGADO STUDIO');
INSERT INTO company_table values( 668, 'ZuoBuLaiGame');
INSERT INTO company_table values( 669, 'LunarPixel');
INSERT INTO company_table values( 670, 'Alysson Moraes');
INSERT INTO company_table values( 671, 'Creability');
INSERT INTO company_table values( 672, 'Secret Level SRL');
INSERT INTO company_table values( 673, 'Alexey Glinskiy');
INSERT INTO company_table values( 674, 'ÔòÎÃêý?');
INSERT INTO company_table values( 675, 'Red Dot Games');
INSERT INTO company_table values( 676, 'YarGri');
INSERT INTO company_table values( 677, 'Lighthouse Games Studio');
INSERT INTO company_table values( 678, '14 Hours Productions');
INSERT INTO company_table values( 679, 'Apoapsis Studios');
INSERT INTO company_table values( 680, 'Catobyte');
INSERT INTO company_table values( 681, 'Landfall West');
INSERT INTO company_table values( 682, 'Nifflas Games');
INSERT INTO company_table values( 683, 'Thalasse Games');
INSERT INTO company_table values( 684, 'DoubleMoose Games');
INSERT INTO company_table values( 685, 'Camex Games');
INSERT INTO company_table values( 686, 'Igor Rashkuev');
INSERT INTO company_table values( 687, 'PuzzleRoo');
INSERT INTO company_table values( 688, 'GrizzlyGames');
INSERT INTO company_table values( 689, 'Sixteen Tons Entertainment');
INSERT INTO company_table values( 690, 'ß¾ú­«¢«ê«¹ü³äÅ?');
SET DEFINE ON;
