SET DEFINE OFF;
INSERT INTO company_table values( 1, 'Valve');
INSERT INTO company_table values( 2, 'Gearbox Software');
INSERT INTO company_table values( 3, 'Mark Healey');
INSERT INTO company_table values( 4, 'Tripwire Interactive');
INSERT INTO company_table values( 5, 'Ritual Entertainment');
INSERT INTO company_table values( 6, 'Introversion Software');
INSERT INTO company_table values( 7, 'Sonalysts');
INSERT INTO company_table values( 8, 'Malfador Machinations');
INSERT INTO company_table values( 9, 'Strategy First');
INSERT INTO company_table values( 10, 'Arkane Studios');
INSERT INTO company_table values( 11, 'Reality Pump Studios');
INSERT INTO company_table values( 12, 'id Software');
INSERT INTO company_table values( 13, 'RavenSoft / id Software');
INSERT INTO company_table values( 14, 'Xatrix Entertainment');
INSERT INTO company_table values( 15, 'Rogue Entertainment');
INSERT INTO company_table values( 16, 'Raven Software');
INSERT INTO company_table values( 17, 'Outerlight Ltd.');
INSERT INTO company_table values( 18, 'Frozenbyte');
INSERT INTO company_table values( 19, 'CINEMAX, s.r.o.');
INSERT INTO company_table values( 20, 'Black Element');
INSERT INTO company_table values( 21, 'Troika Games');
INSERT INTO company_table values( 22, 'Neversoft');
INSERT INTO company_table values( 23, 'Infinity Ward');
INSERT INTO company_table values( 24, 'Aspyr (Mac)');
INSERT INTO company_table values( 25, 'Gray Matter Studios');
INSERT INTO company_table values( 26, 'Frontier');
INSERT INTO company_table values( 27, 'Eugen Systems');
INSERT INTO company_table values( 28, 'Iocaine Studios');
INSERT INTO company_table values( 29, 'Bohemia Interactive');
INSERT INTO company_table values( 30, 'Egosoft');
INSERT INTO company_table values( 31, 'Techland');
INSERT INTO company_table values( 32, '1C Company');
INSERT INTO company_table values( 33, 'Katauri Interactive');
INSERT INTO company_table values( 34, 'Metamorf');
INSERT INTO company_table values( 35, 'Kheops Studio');
INSERT INTO company_table values( 36, 'Mindware Studios');
INSERT INTO company_table values( 37, 'PopCap Games, Inc.');
INSERT INTO company_table values( 38, 'Retro64, Inc.');
INSERT INTO company_table values( 39, 'SpinTop Games');
INSERT INTO company_table values( 40, 'Rebellion');
INSERT INTO company_table values( 41, 'Elixir Studios');
INSERT INTO company_table values( 42, 'GlyphX Games');
INSERT INTO company_table values( 43, 'Terminal Reality');
INSERT INTO company_table values( 44, 'Double Fine Productions');
INSERT INTO company_table values( 45, 'Firaxis Games');
INSERT INTO company_table values( 46, 'FireFly Studios');
INSERT INTO company_table values( 47, 'Facepunch Studios');
INSERT INTO company_table values( 48, 'Funkitron');
INSERT INTO company_table values( 49, 'SimBin');
INSERT INTO company_table values( 50, 'Naked Sky Entertainment');
INSERT INTO company_table values( 51, 'Monte Cristo');
INSERT INTO company_table values( 52, 'GSC Game World');
INSERT INTO company_table values( 53, 'Pandemic Studios');
INSERT INTO company_table values( 54, 'Relic Entertainment');
INSERT INTO company_table values( 55, 'The Creative Assembly');
INSERT INTO company_table values( 56, 'Feral Interactive (Mac)');
INSERT INTO company_table values( 57, 'Feral Interactive (Linux)');
INSERT INTO company_table values( 58, 'Monolith');
INSERT INTO company_table values( 59, 'Unknown Worlds');
INSERT INTO company_table values( 60, 'Unknown Worlds Entertainment');
INSERT INTO company_table values( 61, 'LucasArts');
INSERT INTO company_table values( 62, 'Planet Moon Studios');
INSERT INTO company_table values( 63, 'Klei Entertainment');
INSERT INTO company_table values( 64, 'Sick Puppies');
INSERT INTO company_table values( 65, 'Deepred');
INSERT INTO company_table values( 66, 'Bugbear Entertainment');
INSERT INTO company_table values( 67, 'Muzzy Lane');
INSERT INTO company_table values( 68, 'Artematica Entertainment');
INSERT INTO company_table values( 69, 'Funcom');
INSERT INTO company_table values( 70, 'Most Wanted Entertainment');
INSERT INTO company_table values( 71, 'Mithis Games');
INSERT INTO company_table values( 72, 'THQ Nordic');
INSERT INTO company_table values( 73, 'CAPCOM Co., Ltd.');
INSERT INTO company_table values( 74, 'R C Knight');
INSERT INTO company_table values( 75, 'Pyro Studios');
INSERT INTO company_table values( 76, 'Io-Interactive A/S');
INSERT INTO company_table values( 77, 'Eidos Interactive');
INSERT INTO company_table values( 78, 'Avalanche Studios');
INSERT INTO company_table values( 79, 'Ion Storm');
INSERT INTO company_table values( 80, 'Crystal Dynamics');
INSERT INTO company_table values( 81, 'BioWare Corporation');
INSERT INTO company_table values( 82, 'Nadeo');
INSERT INTO company_table values( 83, 'Pendulo Studios');
INSERT INTO company_table values( 84, 'Cyanide Studios');
INSERT INTO company_table values( 85, 'Big Fish Games');
INSERT INTO company_table values( 86, 'Best Way');
INSERT INTO company_table values( 87, 'Sky Fallen');
INSERT INTO company_table values( 88, 'IO Interactive');
INSERT INTO company_table values( 89, 'Pivotal Games');
INSERT INTO company_table values( 90, 'Eidos Studio Hungary');
INSERT INTO company_table values( 91, 'Telltale Games');
INSERT INTO company_table values( 92, 'Bizarre Creations');
INSERT INTO company_table values( 93, 'CCP');
INSERT INTO company_table values( 94, 'SimBin Studios AB');
INSERT INTO company_table values( 95, 'Irrational Games');
INSERT INTO company_table values( 96, 'Virtual Programming (Linux)');
INSERT INTO company_table values( 97, 'Aspyr (Mac, Linux)');
INSERT INTO company_table values( 98, 'Silver Wish Games');
INSERT INTO company_table values( 99, 'Gas Powered Games');
INSERT INTO company_table values( 100, 'Kaos Studios');
INSERT INTO company_table values( 101, 'Volition');
INSERT INTO company_table values( 102, 'Cryptic Sea');
INSERT INTO company_table values( 103, 'Spellbound');
INSERT INTO company_table values( 104, 'Haggard Games');
INSERT INTO company_table values( 105, 'InnoGlow');
INSERT INTO company_table values( 106, 'Stormregion');
INSERT INTO company_table values( 107, 'Eden Studios');
INSERT INTO company_table values( 108, 'Krome Studios');
INSERT INTO company_table values( 109, 'ImagineEngline');
INSERT INTO company_table values( 110, 'Incinerator Studios');
INSERT INTO company_table values( 111, 'Artech Studios');
INSERT INTO company_table values( 112, 'Treyarch');
INSERT INTO company_table values( 113, 'Sierra');
INSERT INTO company_table values( 114, 'Saber Interactive');
INSERT INTO company_table values( 115, 'Wanako Games');
INSERT INTO company_table values( 116, 'Radical Entertainment');
INSERT INTO company_table values( 117, 'Electronic Paradise');
INSERT INTO company_table values( 118, 'SPLine');
INSERT INTO company_table values( 119, 'Studio4');
INSERT INTO company_table values( 120, 'studio4');
INSERT INTO company_table values( 121, 'Akella');
INSERT INTO company_table values( 122, 'Frogwares');
INSERT INTO company_table values( 123, 'Meridian4');
INSERT INTO company_table values( 124, 'Buka Entertainment');
INSERT INTO company_table values( 125, 'Lesta Studio');
INSERT INTO company_table values( 126, 'Frogames');
INSERT INTO company_table values( 127, 'IonFX');
INSERT INTO company_table values( 128, '2DEngine.com');
INSERT INTO company_table values( 129, 'Triumph Studios');
INSERT INTO company_table values( 130, 'Virtual Programming');
INSERT INTO company_table values( 131, 'KDV Games');
INSERT INTO company_table values( 132, 'Deep Red Limited');
INSERT INTO company_table values( 133, 'Rockstar North');
INSERT INTO company_table values( 134, 'Rockstar San Diego');
INSERT INTO company_table values( 135, 'Rockstar Toronto');
INSERT INTO company_table values( 136, 'Momentum Digital Media Technologies');
INSERT INTO company_table values( 137, 'Deck13');
INSERT INTO company_table values( 138, 'Parallax Arts Studio');
INSERT INTO company_table values( 139, 'Technetium Games');
INSERT INTO company_table values( 140, 'Deck 13');
INSERT INTO company_table values( 141, 'Mascot Entertainment');
INSERT INTO company_table values( 142, 'Ascaron Entertainment ltd.');
INSERT INTO company_table values( 143, 'Noviy Disk');
INSERT INTO company_table values( 144, 'Lesta Studios Inc');
INSERT INTO company_table values( 145, 'Infinite Interactive');
INSERT INTO company_table values( 146, 'Gamebryo');
INSERT INTO company_table values( 147, 'Virtual Playground');
INSERT INTO company_table values( 148, 'SCS Software');
INSERT INTO company_table values( 149, 'Gabriel Entertainment');
INSERT INTO company_table values( 150, 'Zemnott');
INSERT INTO company_table values( 151, 'BigAnt Studios');
INSERT INTO company_table values( 152, 'Merscom');
INSERT INTO company_table values( 153, 'Babylon');
INSERT INTO company_table values( 154, 'Radon Labs');
INSERT INTO company_table values( 155, 'Liquid Entertainment');
INSERT INTO company_table values( 156, 'Blue Omega Entertainment');
INSERT INTO company_table values( 157, 'Codemasters Studios');
INSERT INTO company_table values( 158, 'Dylan Fitterer');
INSERT INTO company_table values( 159, 'Epic Games, Inc.');
INSERT INTO company_table values( 160, 'Ubisoft');
INSERT INTO company_table values( 161, 'Crytek Studios');
INSERT INTO company_table values( 162, 'Ubisoft Montreal');
INSERT INTO company_table values( 163, 'Kudosoft');
INSERT INTO company_table values( 164, 'Red Storm Entertainment');
INSERT INTO company_table values( 165, 'Ubisoft Bulgaria');
INSERT INTO company_table values( 166, 'Ubisoft Montpellier');
INSERT INTO company_table values( 167, 'Nival');
INSERT INTO company_table values( 168, 'Ubisoft Romania');
INSERT INTO company_table values( 169, 'Darkworks');
INSERT INTO company_table values( 170, 'Ubisoft Blue Byte Studio');
INSERT INTO company_table values( 171, '1C: Maddox Games');
INSERT INTO company_table values( 172, 'Oxeye Game Studio');
INSERT INTO company_table values( 173, 'Dejobaan Games, LLC');
INSERT INTO company_table values( 174, 'Owlchemy Labs');
INSERT INTO company_table values( 175, 'Feral Interactive (Mac/Linux)');
INSERT INTO company_table values( 176, 'Oddworld Inhabitants');
INSERT INTO company_table values( 177, 'Slam');
INSERT INTO company_table values( 178, 'MumboJumbo');
INSERT INTO company_table values( 179, 'Last Day of Work');
INSERT INTO company_table values( 180, 'Queasy Games');
INSERT INTO company_table values( 181, 'blurredVision');
INSERT INTO company_table values( 182, 'Redlynx');
INSERT INTO company_table values( 183, 'Redlynx Ltd');
INSERT INTO company_table values( 184, 'Spark Unlimited');
INSERT INTO company_table values( 185, 'Tilted Mill Entertainment, Inc.');
INSERT INTO company_table values( 186, 'Crytek');
INSERT INTO company_table values( 187, 'Maxis¢â');
INSERT INTO company_table values( 188, 'DICE');
INSERT INTO company_table values( 189, 'EA Black Box');
INSERT INTO company_table values( 190, 'BioWare');
INSERT INTO company_table values( 191, 'EA Redwood Shores');
INSERT INTO company_table values( 192, 'EA Los Angeles');
INSERT INTO company_table values( 193, 'GameConnect');
INSERT INTO company_table values( 194, 'InterWave Studios');
INSERT INTO company_table values( 195, 'Hothead Games');
INSERT INTO company_table values( 196, 'Futuremark');
INSERT INTO company_table values( 197, 'Shorebound Studios');
INSERT INTO company_table values( 198, 'Fakt Software');
INSERT INTO company_table values( 199, '4Head Studios');
INSERT INTO company_table values( 200, 'Hidden Path Entertainment');
INSERT INTO company_table values( 201, 'Inventive Dingo');
INSERT INTO company_table values( 202, 'Broken Rules');
INSERT INTO company_table values( 203, 'Brian Cronin');
INSERT INTO company_table values( 204, 'Dialogue Design');
INSERT INTO company_table values( 205, 'Strawdog Studios Ltd');
INSERT INTO company_table values( 206, 'Blue Byte');
INSERT INTO company_table values( 207, 'Perpetual FX Creative');
INSERT INTO company_table values( 208, 'Reactor Zero');
INSERT INTO company_table values( 209, 'Volition, Inc.');
INSERT INTO company_table values( 210, 'Moonpod');
INSERT INTO company_table values( 211, 'CD PROJEKT RED');
INSERT INTO company_table values( 212, 'Traveller''s Tales');
INSERT INTO company_table values( 213, 'Deadline Games');
INSERT INTO company_table values( 214, 'Monolith Productions, Inc.');
INSERT INTO company_table values( 215, 'Timegate');
INSERT INTO company_table values( 216, 'Day 1 Studios');
INSERT INTO company_table values( 217, 'TT Games');
INSERT INTO company_table values( 218, 'Dark Castle Software');
INSERT INTO company_table values( 219, 'Games Faction');
INSERT INTO company_table values( 220, 'Proper Games');
INSERT INTO company_table values( 221, 'Capcom');
INSERT INTO company_table values( 222, 'Ubisoft Reflections');
INSERT INTO company_table values( 223, 'Ubisoft Shangha?');
INSERT INTO company_table values( 224, '2D BOY');
INSERT INTO company_table values( 225, 'TaleWorlds Entertainment');
INSERT INTO company_table values( 226, 'Frictional Games');
INSERT INTO company_table values( 227, 'Paradox Development Studio');
INSERT INTO company_table values( 228, 'ACE Team');
INSERT INTO company_table values( 229, 'Bethesda Game Studios');
INSERT INTO company_table values( 230, 'Bethesda Game Studios¢ç');
INSERT INTO company_table values( 231, 'Headfirst Productions');
INSERT INTO company_table values( 232, 'Obsidian Entertainment');
INSERT INTO company_table values( 233, 'inXile Entertainment');
INSERT INTO company_table values( 234, 'Apus Software');
INSERT INTO company_table values( 235, 'Three Donkeys LLC');
INSERT INTO company_table values( 236, 'Team17 Digital Ltd');
INSERT INTO company_table values( 237, 'Team17 Software Ltd.');
INSERT INTO company_table values( 238, 'Red Chain Games Ltd.');
INSERT INTO company_table values( 239, 'SQUARE ENIX');
INSERT INTO company_table values( 240, 'Haemimont Games');
INSERT INTO company_table values( 241, 'Realmforge Studios');
INSERT INTO company_table values( 242, 'Vicious Cycle Software, Inc.');
INSERT INTO company_table values( 243, 'Soldak Entertainment');
INSERT INTO company_table values( 244, 'Dovetail Games');
INSERT INTO company_table values( 245, 'OVERKILL Software');
INSERT INTO company_table values( 246, 'NeocoreGames');
INSERT INTO company_table values( 247, 'Bit Blot, LLC');
INSERT INTO company_table values( 248, 'N3V Games');
INSERT INTO company_table values( 249, 'EA - Maxis');
INSERT INTO company_table values( 250, 'Criterion Games');
INSERT INTO company_table values( 251, 'Slightly Mad Studios');
INSERT INTO company_table values( 252, 'Wolfire Games');
INSERT INTO company_table values( 253, 'Mindstorm Studios');
INSERT INTO company_table values( 254, 'Basilisk Games');
INSERT INTO company_table values( 255, 'Playbrains');
INSERT INTO company_table values( 256, 'Black Sea Studios Ltd');
INSERT INTO company_table values( 257, '1C:InoCo');
INSERT INTO company_table values( 258, 'BattleGoat Studios');
INSERT INTO company_table values( 259, 'Nitro Games');
INSERT INTO company_table values( 260, 'Cyberlore');
INSERT INTO company_table values( 261, 'Lazy 8 Studios');
INSERT INTO company_table values( 262, 'Number None');
INSERT INTO company_table values( 263, 'Kloonigames');
INSERT INTO company_table values( 264, 'Tale of Tales');
INSERT INTO company_table values( 265, '49 Games');
INSERT INTO company_table values( 266, 'Mousechief');
INSERT INTO company_table values( 267, 'Red Rocket Games');
INSERT INTO company_table values( 268, 'Llamasoft LTD');
INSERT INTO company_table values( 269, 'DnS Development');
INSERT INTO company_table values( 270, 'KranX Productions');
INSERT INTO company_table values( 271, 'Erik Sved?ng');
INSERT INTO company_table values( 272, 'ArenaNet¢ç');
INSERT INTO company_table values( 273, 'Elecorn');
INSERT INTO company_table values( 274, 'Digital Extremes');
INSERT INTO company_table values( 275, 'Replay Studios');
INSERT INTO company_table values( 276, 'HeR Interactive');
INSERT INTO company_table values( 277, 'TrueThought');
INSERT INTO company_table values( 278, 'Black Jacket Studios');
INSERT INTO company_table values( 279, 'Aspyr Studios');
INSERT INTO company_table values( 280, 'Petroglyph');
INSERT INTO company_table values( 281, 'NovaLogic');
INSERT INTO company_table values( 282, 'Snowblind Studios');
INSERT INTO company_table values( 283, 'Enlight Software Limited');
INSERT INTO company_table values( 284, 'Sigma Team Inc.');
INSERT INTO company_table values( 285, 'Related Designs');
INSERT INTO company_table values( 286, 'Brightside Games');
INSERT INTO company_table values( 287, 'PopTop Software');
INSERT INTO company_table values( 288, 'BreakAway Games');
INSERT INTO company_table values( 289, 'Frog City Software');
INSERT INTO company_table values( 290, 'SkyFallen Entertainment');
INSERT INTO company_table values( 291, '1C');
INSERT INTO company_table values( 292, 'Revolution Software Ltd');
INSERT INTO company_table values( 293, 'Synetic');
INSERT INTO company_table values( 294, '.dat');
INSERT INTO company_table values( 295, 'Zaratustra Productions');
INSERT INTO company_table values( 296, 'Bamtang');
INSERT INTO company_table values( 297, 'DTP');
INSERT INTO company_table values( 298, 'Gunnar Games, Inc.');
INSERT INTO company_table values( 299, 'Altar Games');
INSERT INTO company_table values( 300, 'Centauri Production');
INSERT INTO company_table values( 301, 'Sumo Digital');
INSERT INTO company_table values( 302, 'SEGA');
INSERT INTO company_table values( 303, 'Unicorn Games Studio');
INSERT INTO company_table values( 304, 'SaintXi');
INSERT INTO company_table values( 305, 'Wargaming.net');
INSERT INTO company_table values( 306, 'City Interactive');
INSERT INTO company_table values( 307, 'Invent4 Entertainment');
INSERT INTO company_table values( 308, 'Honeyslug');
INSERT INTO company_table values( 309, 'Rocksteady Studios');
INSERT INTO company_table values( 310, 'GFI Russia');
INSERT INTO company_table values( 311, 'Targem Games');
INSERT INTO company_table values( 312, 'Teotl Studios');
INSERT INTO company_table values( 313, 'Power of 2');
INSERT INTO company_table values( 314, 'Frima');
INSERT INTO company_table values( 315, 'Sakari Indie');
INSERT INTO company_table values( 316, 'Sandlot Games');
INSERT INTO company_table values( 317, 'Cateia Games');
INSERT INTO company_table values( 318, '3000AD');
INSERT INTO company_table values( 319, 'FromSoftware');
INSERT INTO company_table values( 320, 'Chaos Concept');
INSERT INTO company_table values( 321, 'Citeremis Inc.');
INSERT INTO company_table values( 322, 'Big Splash Games, LLC');
INSERT INTO company_table values( 323, 'Aliasworlds Entertainment');
INSERT INTO company_table values( 324, 'PlayFirst');
INSERT INTO company_table values( 325, 'Wadjet Eye Games');
INSERT INTO company_table values( 326, 'Sarbakan');
INSERT INTO company_table values( 327, 'Absolutist Ltd.');
INSERT INTO company_table values( 328, 'Size Five Games');
INSERT INTO company_table values( 329, 'Yullaby');
INSERT INTO company_table values( 330, 'Vectorpark, Inc.');
INSERT INTO company_table values( 331, '8monkey Labs');
INSERT INTO company_table values( 332, 'Gamerizon');
INSERT INTO company_table values( 333, 'iWin');
INSERT INTO company_table values( 334, 'Hip Soft');
INSERT INTO company_table values( 335, 'Alawar');
INSERT INTO company_table values( 336, 'Awem Studio');
INSERT INTO company_table values( 337, 'Enlight Software Limited, PerspectX');
INSERT INTO company_table values( 338, 'Interplay Inc.');
INSERT INTO company_table values( 339, 'Black Isle Studios');
INSERT INTO company_table values( 340, '14¡Æ East');
INSERT INTO company_table values( 341, 'Shiny Entertainment');
INSERT INTO company_table values( 342, 'Subsoap');
INSERT INTO company_table values( 343, 'Two Tribes');
INSERT INTO company_table values( 344, 'Square Enix');
INSERT INTO company_table values( 345, 'Freeze Tag Inc.');
INSERT INTO company_table values( 346, 'Joju Games');
INSERT INTO company_table values( 347, 'Linksolutions Ltd.');
INSERT INTO company_table values( 348, 'Dekovir Entertainment');
INSERT INTO company_table values( 349, 'iQ212');
INSERT INTO company_table values( 350, 'Piranha Bytes');
INSERT INTO company_table values( 351, '4HEAD Studios');
INSERT INTO company_table values( 352, 'Phenomic');
INSERT INTO company_table values( 353, 'Homegrown Games');
INSERT INTO company_table values( 354, '4 Head Studios');
INSERT INTO company_table values( 355, 'Cauldron');
INSERT INTO company_table values( 356, 'Rune Forge');
INSERT INTO company_table values( 357, 'Spellbound Studios');
INSERT INTO company_table values( 358, 'DiezelPower');
INSERT INTO company_table values( 359, 'ZoopTEK');
INSERT INTO company_table values( 360, 'Sabi Games');
INSERT INTO company_table values( 361, 'Animation Arts');
INSERT INTO company_table values( 362, 'Arcen Games, LLC');
INSERT INTO company_table values( 363, 'Makivision Games');
INSERT INTO company_table values( 364, 'Amanita Design');
INSERT INTO company_table values( 365, 'Team Meat');
INSERT INTO company_table values( 366, 'Croteam');
INSERT INTO company_table values( 367, 'Konstantin Koshutin');
INSERT INTO company_table values( 368, 'Dream Forge Entertainment, LLC');
INSERT INTO company_table values( 369, 'Runic Games');
INSERT INTO company_table values( 370, 'VIS Interactive');
INSERT INTO company_table values( 371, 'Oasis Games');
INSERT INTO company_table values( 372, 'Independent Programmist Group');
INSERT INTO company_table values( 373, 'Ice-Pick Lodge');
INSERT INTO company_table values( 374, 'Positech Games');
INSERT INTO company_table values( 375, 'Trinoteam');
INSERT INTO company_table values( 376, 'Fatshark');
INSERT INTO company_table values( 377, 'Dark Water Studios Ltd');
INSERT INTO company_table values( 378, 'High Moon Studios');
INSERT INTO company_table values( 379, 'Sledgehammer Games');
INSERT INTO company_table values( 380, 'Crystal Empire Games');
INSERT INTO company_table values( 381, 'BL-Logic');
INSERT INTO company_table values( 382, 'Kerberos Productions Inc.');
INSERT INTO company_table values( 383, 'Arrowhead Game Studios');
INSERT INTO company_table values( 384, 'NeoCoreGames');
INSERT INTO company_table values( 385, 'Kerberos Productions');
INSERT INTO company_table values( 386, 'Double Helix Games');
INSERT INTO company_table values( 387, 'Blue Fang');
INSERT INTO company_table values( 388, 'KTX Software');
INSERT INTO company_table values( 389, 'Hassey Enterprises, Inc.');
INSERT INTO company_table values( 390, 'Codemasters Action Studio');
INSERT INTO company_table values( 391, 'Codemasters Racing');
INSERT INTO company_table values( 392, 'Codemasters Birmingham');
INSERT INTO company_table values( 393, 'Cadenza Interactive');
INSERT INTO company_table values( 394, 'Gaijin Entertainment');
INSERT INTO company_table values( 395, 'Nemesys Games');
INSERT INTO company_table values( 396, 'Airtight Games');
INSERT INTO company_table values( 397, 'CAPCOM CO., LTD.');
INSERT INTO company_table values( 398, 'Other Ocean Interactive');
INSERT INTO company_table values( 399, 'Capcom Vancouver');
INSERT INTO company_table values( 400, 'Ludosity');
INSERT INTO company_table values( 401, 'SkyRiver Studios');
INSERT INTO company_table values( 402, 'The Farm 51');
INSERT INTO company_table values( 403, 'Elite Games Team');
INSERT INTO company_table values( 404, 'X-Bow Software');
INSERT INTO company_table values( 405, 'SoftLab-NSK');
INSERT INTO company_table values( 406, 'Headup Games');
INSERT INTO company_table values( 407, 'Clockstone');
INSERT INTO company_table values( 408, 'ClockStone Studios');
INSERT INTO company_table values( 409, 'Headup Games / Radon Labs');
INSERT INTO company_table values( 410, 'Microids');
INSERT INTO company_table values( 411, 'Octane Games');
INSERT INTO company_table values( 412, 'Headup Games / Crenetic');
INSERT INTO company_table values( 413, 'MC2');
INSERT INTO company_table values( 414, 'Silent Dreams');
INSERT INTO company_table values( 415, 'Dedication Games');
INSERT INTO company_table values( 416, 'Totem Games');
INSERT INTO company_table values( 417, 'Dagger Games');
INSERT INTO company_table values( 418, 'Icehole Games');
INSERT INTO company_table values( 419, 'Darkling Room');
INSERT INTO company_table values( 420, 'Muzzy Lane Software');
INSERT INTO company_table values( 421, 'Ntronium Games');
INSERT INTO company_table values( 422, 'Totem games');
INSERT INTO company_table values( 423, 'Dust Devil Studios Inc.');
INSERT INTO company_table values( 424, 'Playrix Entertainment');
INSERT INTO company_table values( 425, 'Gogii');
INSERT INTO company_table values( 426, 'Visceral Games');
INSERT INTO company_table values( 427, 'Electronic Arts');
INSERT INTO company_table values( 428, 'Stainless Games');
INSERT INTO company_table values( 429, 'The Sims Studio');
INSERT INTO company_table values( 430, 'Playdead');
INSERT INTO company_table values( 431, 'Exkee');
INSERT INTO company_table values( 432, 'Blackhole');
INSERT INTO company_table values( 433, 'VStep');
INSERT INTO company_table values( 434, 'Vanguard Games');
INSERT INTO company_table values( 435, 'Stainless Games Ltd');
INSERT INTO company_table values( 436, 'Cold Beam Games');
INSERT INTO company_table values( 437, 'Beatnik Games');
INSERT INTO company_table values( 438, 'Noumenon Games');
INSERT INTO company_table values( 439, 'doublesix');
INSERT INTO company_table values( 440, 'Big Fish Studios');
INSERT INTO company_table values( 441, 'Blendo Games');
INSERT INTO company_table values( 442, 'Rainbow Studios');
INSERT INTO company_table values( 443, 'Over the Top Games');
INSERT INTO company_table values( 444, 'Doctor Entertainment AB');
INSERT INTO company_table values( 445, 'Gaming Minds Studios');
INSERT INTO company_table values( 446, 'Mediatonic');
INSERT INTO company_table values( 447, 'Stickmen Studios');
INSERT INTO company_table values( 448, 'Brawsome');
INSERT INTO company_table values( 449, 'Binary Takeover');
INSERT INTO company_table values( 450, '4sdk');
INSERT INTO company_table values( 451, 'YeaBoing');
INSERT INTO company_table values( 452, 'Cipher Prime Studios');
INSERT INTO company_table values( 453, 'Secret Exit Ltd.');
INSERT INTO company_table values( 454, 'Capybara Games');
INSERT INTO company_table values( 455, 'Firemint');
INSERT INTO company_table values( 456, 'Zo? Mode');
INSERT INTO company_table values( 457, 'Big Sandwich Games');
INSERT INTO company_table values( 458, 'bitComposer Games');
INSERT INTO company_table values( 459, 'Uber Entertainment');
INSERT INTO company_table values( 460, 'Ronimo Games');
INSERT INTO company_table values( 461, 'Cyan Worlds');
SET DEFINE ON;
