SET DEFINE OFF;
INSERT INTO company_table values( 1, 'Valve');
INSERT INTO company_table values( 2, 'Gearbox Software');
INSERT INTO company_table values( 3, 'Tripwire Interactive');
INSERT INTO company_table values( 4, 'id Software');
INSERT INTO company_table values( 5, 'PopCap Games, Inc.');
INSERT INTO company_table values( 6, 'Elixir Studios');
INSERT INTO company_table values( 7, 'Double Fine Productions');
INSERT INTO company_table values( 8, 'Facepunch Studios');
INSERT INTO company_table values( 9, 'Relic Entertainment');
INSERT INTO company_table values( 10, 'The Creative Assembly');
INSERT INTO company_table values( 11, 'Feral Interactive (Mac)');
INSERT INTO company_table values( 12, 'Feral Interactive (Linux)');
INSERT INTO company_table values( 13, 'Ion Storm');
INSERT INTO company_table values( 14, 'Nadeo');
INSERT INTO company_table values( 15, 'Firaxis Games');
INSERT INTO company_table values( 16, 'Irrational Games');
INSERT INTO company_table values( 17, 'Aspyr (Mac)');
INSERT INTO company_table values( 18, 'Virtual Programming (Linux)');
INSERT INTO company_table values( 19, 'Aspyr (Mac, Linux)');
INSERT INTO company_table values( 20, 'Gas Powered Games');
INSERT INTO company_table values( 21, 'Infinity Ward');
INSERT INTO company_table values( 22, 'Dylan Fitterer');
INSERT INTO company_table values( 23, 'Epic Games, Inc.');
INSERT INTO company_table values( 24, 'Crytek');
INSERT INTO company_table values( 25, 'Maxis¢â');
INSERT INTO company_table values( 26, 'Hidden Path Entertainment');
INSERT INTO company_table values( 27, 'CD PROJEKT RED');
INSERT INTO company_table values( 28, 'TaleWorlds Entertainment');
INSERT INTO company_table values( 29, 'Frictional Games');
INSERT INTO company_table values( 30, 'Bethesda Game Studios');
INSERT INTO company_table values( 31, 'Obsidian Entertainment');
INSERT INTO company_table values( 32, 'BioWare');
INSERT INTO company_table values( 33, 'LucasArts');
INSERT INTO company_table values( 34, 'NovaLogic');
INSERT INTO company_table values( 35, 'Ritual Entertainment');
INSERT INTO company_table values( 36, 'Ubisoft Montreal');
INSERT INTO company_table values( 37, 'Rocksteady Studios');
INSERT INTO company_table values( 38, 'Frozenbyte');
INSERT INTO company_table values( 39, 'Square Enix');
INSERT INTO company_table values( 40, 'Amanita Design');
INSERT INTO company_table values( 41, 'Team Meat');
INSERT INTO company_table values( 42, 'FireFly Studios');
INSERT INTO company_table values( 43, 'Croteam');
INSERT INTO company_table values( 44, 'GSC Game World');
INSERT INTO company_table values( 45, 'Sledgehammer Games');
INSERT INTO company_table values( 46, 'Visceral Games');
INSERT INTO company_table values( 47, 'Criterion Games');
INSERT INTO company_table values( 48, 'The Sims Studio');
INSERT INTO company_table values( 49, 'Cold Beam Games');
INSERT INTO company_table values( 50, 'Volition');
INSERT INTO company_table values( 51, 'Terry Cavanagh');
INSERT INTO company_table values( 52, 'EasyGameStation');
INSERT INTO company_table values( 53, 'Zachtronics');
INSERT INTO company_table values( 54, 'Final Form Games');
INSERT INTO company_table values( 55, 'Gaslamp Games, Inc.');
INSERT INTO company_table values( 56, 'Re-Logic');
INSERT INTO company_table values( 57, 'Supergiant Games');
INSERT INTO company_table values( 58, 'Bohemia Interactive');
INSERT INTO company_table values( 59, 'The Indie Stone');
INSERT INTO company_table values( 60, 'Crytek Studios');
INSERT INTO company_table values( 61, 'Edmund McMillen and Florian Himsl');
INSERT INTO company_table values( 62, 'Runic Games');
INSERT INTO company_table values( 63, 'Nicalis, Inc.');
INSERT INTO company_table values( 64, 'Studio Pixel');
INSERT INTO company_table values( 65, 'Robot Entertainment');
INSERT INTO company_table values( 66, 'Machine Games');
INSERT INTO company_table values( 67, 'Treyarch');
INSERT INTO company_table values( 68, 'The Behemoth');
INSERT INTO company_table values( 69, 'Techland');
INSERT INTO company_table values( 70, 'Arkane Studios');
INSERT INTO company_table values( 71, 'Suspicious Developments');
INSERT INTO company_table values( 72, 'Freebird Games');
INSERT INTO company_table values( 73, 'BlinkWorks Media');
INSERT INTO company_table values( 74, 'Nihon Falcom');
INSERT INTO company_table values( 75, 'Telltale Games');
INSERT INTO company_table values( 76, 'Love Conquers All Games');
INSERT INTO company_table values( 77, 'Thekla, Inc.');
INSERT INTO company_table values( 78, 'Looking Glass Studios');
INSERT INTO company_table values( 79, 'Chucklefish');
INSERT INTO company_table values( 80, 'Sumo Digital');
INSERT INTO company_table values( 81, 'Subset Games');
INSERT INTO company_table values( 82, 'Larian Studios');
INSERT INTO company_table values( 83, 'SNK Games');
INSERT INTO company_table values( 84, 'Elemental Games');
INSERT INTO company_table values( 85, 'Katauri Interactive');
INSERT INTO company_table values( 86, 'Creative Assembly');
INSERT INTO company_table values( 87, 'Daybreak Game Company');
INSERT INTO company_table values( 88, 'Level Up Labs, LLC');
INSERT INTO company_table values( 89, 'Crate Entertainment');
INSERT INTO company_table values( 90, 'Squad');
INSERT INTO company_table values( 91, 'Ubisoft Montreal, Massive Entertainment, and Ubisoft Shanghai');
INSERT INTO company_table values( 92, 'New World Interactive');
INSERT INTO company_table values( 93, 'Megadev');
INSERT INTO company_table values( 94, 'Starbreeze Studios AB');
INSERT INTO company_table values( 95, 'Wormwood Studios');
INSERT INTO company_table values( 96, 'Minority Media Inc.');
INSERT INTO company_table values( 97, 'Rebellion');
INSERT INTO company_table values( 98, 'SCS Software');
INSERT INTO company_table values( 99, 'Shiny Shoe');
INSERT INTO company_table values( 100, 'Metanet Software Inc.');
INSERT INTO company_table values( 101, 'Giant Army');
INSERT INTO company_table values( 102, 'Olli Harjola, Otto Hantula, Tom Jubert, Carlo Castellano');
INSERT INTO company_table values( 103, 'Introversion Software');
INSERT INTO company_table values( 104, 'Anti Matter Games');
INSERT INTO company_table values( 105, 'CyberConnect2 Co. Ltd.');
INSERT INTO company_table values( 106, 'Ubisoft Toronto');
INSERT INTO company_table values( 107, 'Humble Hearts LLC');
INSERT INTO company_table values( 108, 'Gaijin Entertainment');
INSERT INTO company_table values( 109, 'FromSoftware, Inc');
INSERT INTO company_table values( 110, 'Mine Loader Software Co., Ltd.');
INSERT INTO company_table values( 111, 'Red Barrels');
INSERT INTO company_table values( 112, '3909');
INSERT INTO company_table values( 113, 'Monolith Productions');
INSERT INTO company_table values( 114, 'Vlambeer');
INSERT INTO company_table values( 115, 'Carlsen Games');
INSERT INTO company_table values( 116, 'Shining Rock Software LLC');
INSERT INTO company_table values( 117, 'Lab Zero Games');
INSERT INTO company_table values( 118, 'Ironhide Game Studio');
INSERT INTO company_table values( 119, 'Ndemic Creations');
INSERT INTO company_table values( 120, 'Vertigo Gaming Inc.');
INSERT INTO company_table values( 121, 'Brace Yourself Games');
INSERT INTO company_table values( 122, 'GalaxyTrail');
INSERT INTO company_table values( 123, 'Hopoo Games, LLC');
INSERT INTO company_table values( 124, 'Infinite Monkeys Entertainment Ltd.');
INSERT INTO company_table values( 125, 'Eugen Systems');
INSERT INTO company_table values( 126, 'Hanako Games');
INSERT INTO company_table values( 127, 'Asteroid Base');
INSERT INTO company_table values( 128, 'Rocketcat Games');
INSERT INTO company_table values( 129, 'Madgarden');
INSERT INTO company_table values( 130, 'Psyonix, Inc.');
INSERT INTO company_table values( 131, 'Gears for Breakfast');
INSERT INTO company_table values( 132, 'Treasure');
INSERT INTO company_table values( 133, 'Colossal Order Ltd.');
INSERT INTO company_table values( 134, 'Heart Machine');
INSERT INTO company_table values( 135, 'Netcore Games');
INSERT INTO company_table values( 136, 'Ubisoft Montpellier');
INSERT INTO company_table values( 137, 'JoWooD Vienna');
INSERT INTO company_table values( 138, 'Team Reptile');
INSERT INTO company_table values( 139, 'Moon Studios GmbH');
INSERT INTO company_table values( 140, 'Red Hook Studios');
INSERT INTO company_table values( 141, 'Silver Dollar Games');
INSERT INTO company_table values( 142, 'Unknown Worlds Entertainment');
INSERT INTO company_table values( 143, 'Matt Roszak');
INSERT INTO company_table values( 144, 'Matthew Brown');
INSERT INTO company_table values( 145, 'Thomas Bowker');
INSERT INTO company_table values( 146, 'Defiant Development');
INSERT INTO company_table values( 147, 'Firaxis');
INSERT INTO company_table values( 148, 'StudioMDHR Entertainment Inc.');
INSERT INTO company_table values( 149, 'Laminar Research');
INSERT INTO company_table values( 150, 'Dennaton Games');
INSERT INTO company_table values( 151, 'Free Lives');
INSERT INTO company_table values( 152, 'Tendershoot');
INSERT INTO company_table values( 153, 'A Jolly Corpse');
INSERT INTO company_table values( 154, 'Stellar Jockeys');
INSERT INTO company_table values( 155, 'Gausswerks');
INSERT INTO company_table values( 156, 'Alastair John Jack');
INSERT INTO company_table values( 157, 'Paradox Development Studio');
INSERT INTO company_table values( 158, '11 bit studios');
INSERT INTO company_table values( 159, 'YOTSUBANE');
INSERT INTO company_table values( 160, 'Adventure Planning Service');
INSERT INTO company_table values( 161, 'Boneloaf');
INSERT INTO company_table values( 162, 'Pocketwatch Games');
INSERT INTO company_table values( 163, 'Berserk Games');
INSERT INTO company_table values( 164, 'ALICE IN DISSONANCE');
INSERT INTO company_table values( 165, '4A Games');
INSERT INTO company_table values( 166, 'Konami Digital Entertainment');
INSERT INTO company_table values( 167, 'Dinosaur Polo Club');
INSERT INTO company_table values( 168, 'Fireproof Games');
INSERT INTO company_table values( 169, 'League of Geeks');
INSERT INTO company_table values( 170, 'Powerhoof');
INSERT INTO company_table values( 171, 'Ludeon Studios');
INSERT INTO company_table values( 172, 'Game in a Bottle');
INSERT INTO company_table values( 173, 'Cavedog Entertainment');
INSERT INTO company_table values( 174, 'Ubisoft Montreal, Red Storm, Shanghai, Toronto, Kiev');
INSERT INTO company_table values( 175, 'Hinterland Studio Inc.');
INSERT INTO company_table values( 176, 'Ninja Kiwi');
INSERT INTO company_table values( 177, 'Zenimax Online Studios');
INSERT INTO company_table values( 178, 'Mediatonic');
INSERT INTO company_table values( 179, 'Hato Moa');
INSERT INTO company_table values( 180, 'The Irregular Corporation');
INSERT INTO company_table values( 181, '07th Expansion');
INSERT INTO company_table values( 182, 'Capcom');
INSERT INTO company_table values( 183, 'Ubisoft Sofia');
INSERT INTO company_table values( 184, 'Ubisoft Kiev');
INSERT INTO company_table values( 185, 'Dodge Roll');
INSERT INTO company_table values( 186, 'Videocult');
INSERT INTO company_table values( 187, 'minori');
INSERT INTO company_table values( 188, 'VisualArts/Key');
INSERT INTO company_table values( 189, 'Heartbit Interactive');
INSERT INTO company_table values( 190, 'DONTNOD Entertainment');
INSERT INTO company_table values( 191, 'Batterystaple Games');
INSERT INTO company_table values( 192, 'Fire Hose Games');
INSERT INTO company_table values( 193, 'RobTop Games');
INSERT INTO company_table values( 194, 'Image & Form');
INSERT INTO company_table values( 195, 'Klei Entertainment');
INSERT INTO company_table values( 196, 'Indimo Labs LLC');
INSERT INTO company_table values( 197, 'THQ Nordic');
INSERT INTO company_table values( 198, 'CAPCOM Co., Ltd.');
INSERT INTO company_table values( 199, 'Soviet Games');
INSERT INTO company_table values( 200, 'KOEI TECMO GAMES CO., LTD.');
INSERT INTO company_table values( 201, 'Thomas Happ Games LLC');
INSERT INTO company_table values( 202, 'Freehold Games');
INSERT INTO company_table values( 203, 'Dingaling');
INSERT INTO company_table values( 204, 'Sujin Ri');
INSERT INTO company_table values( 205, 'Yunjeong Yun');
INSERT INTO company_table values( 206, 'Hyein Go');
INSERT INTO company_table values( 207, 'Minsu Ock');
INSERT INTO company_table values( 208, 'Marcos Arroyo');
INSERT INTO company_table values( 209, 'Seona Lee');
INSERT INTO company_table values( 210, 'Sohyeon Jeon');
INSERT INTO company_table values( 211, 'Choice of Games');
INSERT INTO company_table values( 212, 'KIXEYE');
INSERT INTO company_table values( 213, 'Steel Crate Games');
INSERT INTO company_table values( 214, 'David Stark');
INSERT INTO company_table values( 215, 'Shorebound Studios');
INSERT INTO company_table values( 216, 'Frontwing');
INSERT INTO company_table values( 217, 'WayForward');
INSERT INTO company_table values( 218, 'Spiderling Studios');
INSERT INTO company_table values( 219, 'Studio Wildcard');
INSERT INTO company_table values( 220, 'Instinct Games');
INSERT INTO company_table values( 221, 'Efecto Studios');
INSERT INTO company_table values( 222, 'Virtual Basement LLC');
INSERT INTO company_table values( 223, 'ÍÔÍÅ??êÍ??');
INSERT INTO company_table values( 224, 'Ð¹í­Úì');
INSERT INTO company_table values( 225, 'MachineGames');
INSERT INTO company_table values( 226, 'Holy Priest');
INSERT INTO company_table values( 227, 'BANDAI NAMCO Studio Inc.');
INSERT INTO company_table values( 228, 'Valsar');
INSERT INTO company_table values( 229, 'Moppin');
INSERT INTO company_table values( 230, 'System Era Softworks');
INSERT INTO company_table values( 231, 'Killmonday Games AB');
INSERT INTO company_table values( 232, 'Team Fractal Alligator');
INSERT INTO company_table values( 233, 'Massive Entertainment');
INSERT INTO company_table values( 234, 'Pipliz');
INSERT INTO company_table values( 235, 'Dry Cactus');
INSERT INTO company_table values( 236, 'Team Cherry');
INSERT INTO company_table values( 237, 'Maciej Targoni');
INSERT INTO company_table values( 238, 'Wojciech Wasiak');
INSERT INTO company_table values( 239, 'Radical Fish Games');
INSERT INTO company_table values( 240, 'Robot Gentleman');
INSERT INTO company_table values( 241, 'Trese Brothers');
INSERT INTO company_table values( 242, '¡â¡Û¡à¡¿ (Miwashiba)');
INSERT INTO company_table values( 243, 'FromSoftware, Inc.');
INSERT INTO company_table values( 244, 'Subworld');
INSERT INTO company_table values( 245, 'CAVE Interactive CO.,LTD.');
INSERT INTO company_table values( 246, 'Slightly Mad Studios');
INSERT INTO company_table values( 247, 'Campo Santo');
INSERT INTO company_table values( 248, 'Giant Squid');
INSERT INTO company_table values( 249, 'BANDAI NAMCO Studios Inc.');
INSERT INTO company_table values( 250, 'Crystal Dynamics');
INSERT INTO company_table values( 251, 'tobyfox');
INSERT INTO company_table values( 252, 'Bloober Team SA');
INSERT INTO company_table values( 253, 'AMPLITUDE Studios');
INSERT INTO company_table values( 254, 'Jesse Makkonen');
INSERT INTO company_table values( 255, 'PixelFade Inc');
INSERT INTO company_table values( 256, 'ROCKFISH Games');
INSERT INTO company_table values( 257, 'Fishing Cactus');
INSERT INTO company_table values( 258, 'Knuist & Perzik');
INSERT INTO company_table values( 259, 'CreSpirit');
INSERT INTO company_table values( 260, 'GemaYue');
INSERT INTO company_table values( 261, 'Daniel Mullins Games');
INSERT INTO company_table values( 262, 'Iguana Entertainment');
INSERT INTO company_table values( 263, 'Nightdive Studios');
INSERT INTO company_table values( 264, 'Nippon Ichi Software, Inc.');
INSERT INTO company_table values( 265, 'Dominique Grieshofer');
INSERT INTO company_table values( 266, 'Ludosity');
INSERT INTO company_table values( 267, 'Remar Games');
INSERT INTO company_table values( 268, 'Tamsoft');
INSERT INTO company_table values( 269, 'Krome Studios');
INSERT INTO company_table values( 270, 'MAGES. Inc.');
INSERT INTO company_table values( 271, 'ConcernedApe');
INSERT INTO company_table values( 272, 'Spike Chunsoft Co., Ltd.');
INSERT INTO company_table values( 273, 'Abstraction Games');
INSERT INTO company_table values( 274, 'Antimatter Games');
INSERT INTO company_table values( 275, 'I-Illusions');
INSERT INTO company_table values( 276, 'Little Cat Feet');
INSERT INTO company_table values( 277, 'Codemasters');
INSERT INTO company_table values( 278, 'Sorath');
INSERT INTO company_table values( 279, 'SnoutUp');
INSERT INTO company_table values( 280, 'Tarsier Studios');
INSERT INTO company_table values( 281, 'Wube Software LTD.');
INSERT INTO company_table values( 282, 'Morenori Soft');
INSERT INTO company_table values( 283, 'Bombservice');
INSERT INTO company_table values( 284, 'Modern Visual Arts Laboratory');
INSERT INTO company_table values( 285, 'SEO INSEOK');
INSERT INTO company_table values( 286, 'Monomi Park');
INSERT INTO company_table values( 287, 'Nickervision Studios');
INSERT INTO company_table values( 288, 'Big Corporation');
INSERT INTO company_table values( 289, 'Adriaan de Jongh');
INSERT INTO company_table values( 290, 'Sylvain Tegroeg');
INSERT INTO company_table values( 291, 'Survios');
INSERT INTO company_table values( 292, 'Aldin Dynamics');
INSERT INTO company_table values( 293, 'Hi-Rez Studios');
INSERT INTO company_table values( 294, 'Wargaming Group Limited');
INSERT INTO company_table values( 295, 'Big Fat Simulations Inc.');
INSERT INTO company_table values( 296, 'Giants Software');
INSERT INTO company_table values( 297, 'Ubisoft');
INSERT INTO company_table values( 298, 'Sukeban Games');
INSERT INTO company_table values( 299, 'Owlchemy Labs');
INSERT INTO company_table values( 300, 'Thing Trunk');
INSERT INTO company_table values( 301, 'Revival Productions, LLC');
INSERT INTO company_table values( 302, 'QLOC');
INSERT INTO company_table values( 303, 'DIMPS');
INSERT INTO company_table values( 304, 'Ensemble Studios');
INSERT INTO company_table values( 305, 'Behaviour Interactive');
INSERT INTO company_table values( 306, '343 Industries');
INSERT INTO company_table values( 307, 'Ubisoft Annecy');
INSERT INTO company_table values( 308, 'Ubisoft Paris');
INSERT INTO company_table values( 309, 'Ubisoft Bucharest');
INSERT INTO company_table values( 310, 'Ubisoft Milan');
INSERT INTO company_table values( 311, 'Reflections');
INSERT INTO company_table values( 312, 'Michal Pawlowski');
INSERT INTO company_table values( 313, 'YETU GAME');
INSERT INTO company_table values( 314, 'Out of the Park Developments');
INSERT INTO company_table values( 315, 'Against Gravity¢ç');
INSERT INTO company_table values( 316, 'No Brakes Games');
INSERT INTO company_table values( 317, 'Infinite Fall');
INSERT INTO company_table values( 318, 'Sports Interactive');
INSERT INTO company_table values( 319, 'sen');
INSERT INTO company_table values( 320, 'Halfbrick Studios Pty Ltd');
INSERT INTO company_table values( 321, 'For Fun Labs');
INSERT INTO company_table values( 322, 'Frontier Developments');
INSERT INTO company_table values( 323, 'Realmforge Studios');
INSERT INTO company_table values( 324, 'oneoreight');
INSERT INTO company_table values( 325, 'JCKSLAP');
INSERT INTO company_table values( 326, 'Rabbiton');
INSERT INTO company_table values( 327, 'Giant Sparrow');
INSERT INTO company_table values( 328, 'Game-Labs');
INSERT INTO company_table values( 329, 'Jutsu Games');
INSERT INTO company_table values( 330, 'Everglow Interactive Inc.');
INSERT INTO company_table values( 331, 'Marvelous Inc.');
INSERT INTO company_table values( 332, 'Matt Dabrowski');
INSERT INTO company_table values( 333, 'Maxint LLC');
INSERT INTO company_table values( 334, 'Toast');
INSERT INTO company_table values( 335, 'ProGames Studio');
INSERT INTO company_table values( 336, 'Arc System Works');
INSERT INTO company_table values( 337, 'CFK Co., Ltd.');
INSERT INTO company_table values( 338, 'Kyle Seeley');
INSERT INTO company_table values( 339, 'Rusty Lake');
INSERT INTO company_table values( 340, 'Den-fami Nico Game Magazine');
INSERT INTO company_table values( 341, 'Makoto Sanada');
INSERT INTO company_table values( 342, 'Avalanche Software');
INSERT INTO company_table values( 343, 'Heavy Iron Studios');
INSERT INTO company_table values( 344, '10Ants Hill');
INSERT INTO company_table values( 345, 'Laura Shigihara');
INSERT INTO company_table values( 346, 'Quiet River');
INSERT INTO company_table values( 347, 'Project Moon');
INSERT INTO company_table values( 348, 'SNK CORPORATION');
INSERT INTO company_table values( 349, 'Visual Concepts');
INSERT INTO company_table values( 350, 'Prideful Sloth');
INSERT INTO company_table values( 351, 'Christian Whitehead');
INSERT INTO company_table values( 352, 'Headcannon');
INSERT INTO company_table values( 353, 'PagodaWest Games');
INSERT INTO company_table values( 354, '4D Door Games');
INSERT INTO company_table values( 355, 'Motion Twin');
INSERT INTO company_table values( 356, 'Anvil Game Studios');
INSERT INTO company_table values( 357, 'Konami Digital Entertainment Co., Ltd.');
INSERT INTO company_table values( 358, 'The Gentlebros');
INSERT INTO company_table values( 359, 'Doborog Games');
INSERT INTO company_table values( 360, 'Asymmetric');
INSERT INTO company_table values( 361, 'AQURIA');
INSERT INTO company_table values( 362, 'tri-Ace');
INSERT INTO company_table values( 363, 'SUPERHOT Team');
INSERT INTO company_table values( 364, 'What Pumpkin Games, Inc.');
INSERT INTO company_table values( 365, 'Creability');
INSERT INTO company_table values( 366, 'TT Games');
INSERT INTO company_table values( 367, 'HFM Games');
INSERT INTO company_table values( 368, 'Lighthouse Games Studio');
INSERT INTO company_table values( 369, 'Landfall West');
INSERT INTO company_table values( 370, 'GrizzlyGames');
INSERT INTO company_table values( 371, 'ß¾ú­«¢«ê«¹ü³äÅ?');
SET DEFINE ON;
