SET DEFINE OFF;
INSERT	INTO	Language_table		VALUES(			1,			'Simplified Chinese'	)
INSERT	INTO	Language_table		VALUES(			2,			'English'	)
INSERT	INTO	Language_table		VALUES(			3,			'Italian'	)
INSERT	INTO	Language_table		VALUES(			4,			'French'	)
INSERT	INTO	Language_table		VALUES(			5,			'Korean'	)
INSERT	INTO	Language_table		VALUES(			6,			'German'	)
INSERT	INTO	Language_table		VALUES(			7,			'Spanish'	)
INSERT	INTO	Language_table		VALUES(			8,			'Traditional Chinese'	)
INSERT	INTO	Language_table		VALUES(			9,			'Russian'	)
INSERT	INTO	Language_table		VALUES(			10,			'Polish'	)
INSERT	INTO	Language_table		VALUES(			11,			'Japanese'	)
INSERT	INTO	Language_table		VALUES(			12,			'Swedish'	)
INSERT	INTO	Language_table		VALUES(			13,			'Portuguese'	)
INSERT	INTO	Language_table		VALUES(			14,			'Danish'	)
INSERT	INTO	Language_table		VALUES(			15,			'Finnish'	)
INSERT	INTO	Language_table		VALUES(			16,			'Thai'	)
INSERT	INTO	Language_table		VALUES(			17,			'Dutch'	)
INSERT	INTO	Language_table		VALUES(			18,			'Norwegian'	)
INSERT	INTO	Language_table		VALUES(			19,			'Turkish'	)
INSERT	INTO	Language_table		VALUES(			20,			'Portuguese-Brazil'	)
INSERT	INTO	Language_table		VALUES(			21,			'Ukrainian'	)
INSERT	INTO	Language_table		VALUES(			22,			'Romanian'	)
INSERT	INTO	Language_table		VALUES(			23,			'Bulgarian'	)
INSERT	INTO	Language_table		VALUES(			24,			'Czech'	)
INSERT	INTO	Language_table		VALUES(			25,			'Hungarian'	)
INSERT	INTO	Language_table		VALUES(			26,			'Greek'	)
INSERT	INTO	Language_table		VALUES(			27,			'Arabic'	)
SET DEFINE ON;
